// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storage

import (
	"context"
	conditions "github.com/diwise/iot-device-mgmt/internal/pkg/types"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			AddAlarmFunc: func(ctx context.Context, deviceID string, a types.AlarmDetails) error {
//				panic("mock out the AddAlarm method")
//			},
//			AddDeviceStatusFunc: func(ctx context.Context, status types.StatusMessage) error {
//				panic("mock out the AddDeviceStatus method")
//			},
//			AddTagFunc: func(ctx context.Context, deviceID string, t types.Tag) error {
//				panic("mock out the AddTag method")
//			},
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			CreateOrUpdateDeviceFunc: func(ctx context.Context, d types.Device) error {
//				panic("mock out the CreateOrUpdateDevice method")
//			},
//			CreateSensorProfileFunc: func(ctx context.Context, p types.SensorProfile) error {
//				panic("mock out the CreateSensorProfile method")
//			},
//			CreateSensorProfileTypeFunc: func(ctx context.Context, t types.Lwm2mType) error {
//				panic("mock out the CreateSensorProfileType method")
//			},
//			CreateTagFunc: func(ctx context.Context, t types.Tag) error {
//				panic("mock out the CreateTag method")
//			},
//			GetAlarmsFunc: func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Alarms], error) {
//				panic("mock out the GetAlarms method")
//			},
//			GetDeviceAlarmsFunc: func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
//				panic("mock out the GetDeviceAlarms method")
//			},
//			GetDeviceBySensorIDFunc: func(ctx context.Context, sensorID string) (types.Device, error) {
//				panic("mock out the GetDeviceBySensorID method")
//			},
//			GetDeviceMeasurementsFunc: func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error) {
//				panic("mock out the GetDeviceMeasurements method")
//			},
//			GetDeviceStatusFunc: func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error) {
//				panic("mock out the GetDeviceStatus method")
//			},
//			GetStaleDevicesFunc: func(ctx context.Context) (types.Collection[types.Device], error) {
//				panic("mock out the GetStaleDevices method")
//			},
//			GetTenantsFunc: func(ctx context.Context) (types.Collection[string], error) {
//				panic("mock out the GetTenants method")
//			},
//			InitializeFunc: func(ctx context.Context) error {
//				panic("mock out the Initialize method")
//			},
//			IsSeedExistingDevicesEnabledFunc: func(ctx context.Context) bool {
//				panic("mock out the IsSeedExistingDevicesEnabled method")
//			},
//			QueryFunc: func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error) {
//				panic("mock out the Query method")
//			},
//			RemoveAlarmFunc: func(ctx context.Context, deviceID string, alarmType string) error {
//				panic("mock out the RemoveAlarm method")
//			},
//			SetDeviceProfileTypesFunc: func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
//				panic("mock out the SetDeviceProfileTypes method")
//			},
//			SetDeviceStateFunc: func(ctx context.Context, deviceID string, state types.DeviceState) error {
//				panic("mock out the SetDeviceState method")
//			},
//			SetSensorProfileFunc: func(ctx context.Context, deviceID string, dp types.SensorProfile) error {
//				panic("mock out the SetSensorProfile method")
//			},
//			UpdateDeviceFunc: func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
//				panic("mock out the UpdateDevice method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AddAlarmFunc mocks the AddAlarm method.
	AddAlarmFunc func(ctx context.Context, deviceID string, a types.AlarmDetails) error

	// AddDeviceStatusFunc mocks the AddDeviceStatus method.
	AddDeviceStatusFunc func(ctx context.Context, status types.StatusMessage) error

	// AddTagFunc mocks the AddTag method.
	AddTagFunc func(ctx context.Context, deviceID string, t types.Tag) error

	// CloseFunc mocks the Close method.
	CloseFunc func()

	// CreateOrUpdateDeviceFunc mocks the CreateOrUpdateDevice method.
	CreateOrUpdateDeviceFunc func(ctx context.Context, d types.Device) error

	// CreateSensorProfileFunc mocks the CreateSensorProfile method.
	CreateSensorProfileFunc func(ctx context.Context, p types.SensorProfile) error

	// CreateSensorProfileTypeFunc mocks the CreateSensorProfileType method.
	CreateSensorProfileTypeFunc func(ctx context.Context, t types.Lwm2mType) error

	// CreateTagFunc mocks the CreateTag method.
	CreateTagFunc func(ctx context.Context, t types.Tag) error

	// GetAlarmsFunc mocks the GetAlarms method.
	GetAlarmsFunc func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Alarms], error)

	// GetDeviceAlarmsFunc mocks the GetDeviceAlarms method.
	GetDeviceAlarmsFunc func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error)

	// GetDeviceBySensorIDFunc mocks the GetDeviceBySensorID method.
	GetDeviceBySensorIDFunc func(ctx context.Context, sensorID string) (types.Device, error)

	// GetDeviceMeasurementsFunc mocks the GetDeviceMeasurements method.
	GetDeviceMeasurementsFunc func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error)

	// GetDeviceStatusFunc mocks the GetDeviceStatus method.
	GetDeviceStatusFunc func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error)

	// GetStaleDevicesFunc mocks the GetStaleDevices method.
	GetStaleDevicesFunc func(ctx context.Context) (types.Collection[types.Device], error)

	// GetTenantsFunc mocks the GetTenants method.
	GetTenantsFunc func(ctx context.Context) (types.Collection[string], error)

	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(ctx context.Context) error

	// IsSeedExistingDevicesEnabledFunc mocks the IsSeedExistingDevicesEnabled method.
	IsSeedExistingDevicesEnabledFunc func(ctx context.Context) bool

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error)

	// RemoveAlarmFunc mocks the RemoveAlarm method.
	RemoveAlarmFunc func(ctx context.Context, deviceID string, alarmType string) error

	// SetDeviceProfileTypesFunc mocks the SetDeviceProfileTypes method.
	SetDeviceProfileTypesFunc func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error

	// SetDeviceStateFunc mocks the SetDeviceState method.
	SetDeviceStateFunc func(ctx context.Context, deviceID string, state types.DeviceState) error

	// SetSensorProfileFunc mocks the SetSensorProfile method.
	SetSensorProfileFunc func(ctx context.Context, deviceID string, dp types.SensorProfile) error

	// UpdateDeviceFunc mocks the UpdateDevice method.
	UpdateDeviceFunc func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error

	// calls tracks calls to the methods.
	calls struct {
		// AddAlarm holds details about calls to the AddAlarm method.
		AddAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// A is the a argument value.
			A types.AlarmDetails
		}
		// AddDeviceStatus holds details about calls to the AddDeviceStatus method.
		AddDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status types.StatusMessage
		}
		// AddTag holds details about calls to the AddTag method.
		AddTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// T is the t argument value.
			T types.Tag
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CreateOrUpdateDevice holds details about calls to the CreateOrUpdateDevice method.
		CreateOrUpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// D is the d argument value.
			D types.Device
		}
		// CreateSensorProfile holds details about calls to the CreateSensorProfile method.
		CreateSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P types.SensorProfile
		}
		// CreateSensorProfileType holds details about calls to the CreateSensorProfileType method.
		CreateSensorProfileType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T types.Lwm2mType
		}
		// CreateTag holds details about calls to the CreateTag method.
		CreateTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T types.Tag
		}
		// GetAlarms holds details about calls to the GetAlarms method.
		GetAlarms []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// GetDeviceAlarms holds details about calls to the GetDeviceAlarms method.
		GetDeviceAlarms []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// GetDeviceBySensorID holds details about calls to the GetDeviceBySensorID method.
		GetDeviceBySensorID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// GetDeviceMeasurements holds details about calls to the GetDeviceMeasurements method.
		GetDeviceMeasurements []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// GetDeviceStatus holds details about calls to the GetDeviceStatus method.
		GetDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// GetStaleDevices holds details about calls to the GetStaleDevices method.
		GetStaleDevices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetTenants holds details about calls to the GetTenants method.
		GetTenants []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IsSeedExistingDevicesEnabled holds details about calls to the IsSeedExistingDevicesEnabled method.
		IsSeedExistingDevicesEnabled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// RemoveAlarm holds details about calls to the RemoveAlarm method.
		RemoveAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// AlarmType is the alarmType argument value.
			AlarmType string
		}
		// SetDeviceProfileTypes holds details about calls to the SetDeviceProfileTypes method.
		SetDeviceProfileTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// TypesMoqParam is the typesMoqParam argument value.
			TypesMoqParam []types.Lwm2mType
		}
		// SetDeviceState holds details about calls to the SetDeviceState method.
		SetDeviceState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// State is the state argument value.
			State types.DeviceState
		}
		// SetSensorProfile holds details about calls to the SetSensorProfile method.
		SetSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Dp is the dp argument value.
			Dp types.SensorProfile
		}
		// UpdateDevice holds details about calls to the UpdateDevice method.
		UpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Active is the active argument value.
			Active *bool
			// Name is the name argument value.
			Name *string
			// Description is the description argument value.
			Description *string
			// Environment is the environment argument value.
			Environment *string
			// Source is the source argument value.
			Source *string
			// Tenant is the tenant argument value.
			Tenant *string
			// Location is the location argument value.
			Location *types.Location
			// Interval is the interval argument value.
			Interval *int
		}
	}
	lockAddAlarm                     sync.RWMutex
	lockAddDeviceStatus              sync.RWMutex
	lockAddTag                       sync.RWMutex
	lockClose                        sync.RWMutex
	lockCreateOrUpdateDevice         sync.RWMutex
	lockCreateSensorProfile          sync.RWMutex
	lockCreateSensorProfileType      sync.RWMutex
	lockCreateTag                    sync.RWMutex
	lockGetAlarms                    sync.RWMutex
	lockGetDeviceAlarms              sync.RWMutex
	lockGetDeviceBySensorID          sync.RWMutex
	lockGetDeviceMeasurements        sync.RWMutex
	lockGetDeviceStatus              sync.RWMutex
	lockGetStaleDevices              sync.RWMutex
	lockGetTenants                   sync.RWMutex
	lockInitialize                   sync.RWMutex
	lockIsSeedExistingDevicesEnabled sync.RWMutex
	lockQuery                        sync.RWMutex
	lockRemoveAlarm                  sync.RWMutex
	lockSetDeviceProfileTypes        sync.RWMutex
	lockSetDeviceState               sync.RWMutex
	lockSetSensorProfile             sync.RWMutex
	lockUpdateDevice                 sync.RWMutex
}

// AddAlarm calls AddAlarmFunc.
func (mock *StoreMock) AddAlarm(ctx context.Context, deviceID string, a types.AlarmDetails) error {
	if mock.AddAlarmFunc == nil {
		panic("StoreMock.AddAlarmFunc: method is nil but Store.AddAlarm was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		A        types.AlarmDetails
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		A:        a,
	}
	mock.lockAddAlarm.Lock()
	mock.calls.AddAlarm = append(mock.calls.AddAlarm, callInfo)
	mock.lockAddAlarm.Unlock()
	return mock.AddAlarmFunc(ctx, deviceID, a)
}

// AddAlarmCalls gets all the calls that were made to AddAlarm.
// Check the length with:
//
//	len(mockedStore.AddAlarmCalls())
func (mock *StoreMock) AddAlarmCalls() []struct {
	Ctx      context.Context
	DeviceID string
	A        types.AlarmDetails
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		A        types.AlarmDetails
	}
	mock.lockAddAlarm.RLock()
	calls = mock.calls.AddAlarm
	mock.lockAddAlarm.RUnlock()
	return calls
}

// AddDeviceStatus calls AddDeviceStatusFunc.
func (mock *StoreMock) AddDeviceStatus(ctx context.Context, status types.StatusMessage) error {
	if mock.AddDeviceStatusFunc == nil {
		panic("StoreMock.AddDeviceStatusFunc: method is nil but Store.AddDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status types.StatusMessage
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockAddDeviceStatus.Lock()
	mock.calls.AddDeviceStatus = append(mock.calls.AddDeviceStatus, callInfo)
	mock.lockAddDeviceStatus.Unlock()
	return mock.AddDeviceStatusFunc(ctx, status)
}

// AddDeviceStatusCalls gets all the calls that were made to AddDeviceStatus.
// Check the length with:
//
//	len(mockedStore.AddDeviceStatusCalls())
func (mock *StoreMock) AddDeviceStatusCalls() []struct {
	Ctx    context.Context
	Status types.StatusMessage
} {
	var calls []struct {
		Ctx    context.Context
		Status types.StatusMessage
	}
	mock.lockAddDeviceStatus.RLock()
	calls = mock.calls.AddDeviceStatus
	mock.lockAddDeviceStatus.RUnlock()
	return calls
}

// AddTag calls AddTagFunc.
func (mock *StoreMock) AddTag(ctx context.Context, deviceID string, t types.Tag) error {
	if mock.AddTagFunc == nil {
		panic("StoreMock.AddTagFunc: method is nil but Store.AddTag was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		T        types.Tag
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		T:        t,
	}
	mock.lockAddTag.Lock()
	mock.calls.AddTag = append(mock.calls.AddTag, callInfo)
	mock.lockAddTag.Unlock()
	return mock.AddTagFunc(ctx, deviceID, t)
}

// AddTagCalls gets all the calls that were made to AddTag.
// Check the length with:
//
//	len(mockedStore.AddTagCalls())
func (mock *StoreMock) AddTagCalls() []struct {
	Ctx      context.Context
	DeviceID string
	T        types.Tag
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		T        types.Tag
	}
	mock.lockAddTag.RLock()
	calls = mock.calls.AddTag
	mock.lockAddTag.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *StoreMock) Close() {
	if mock.CloseFunc == nil {
		panic("StoreMock.CloseFunc: method is nil but Store.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStore.CloseCalls())
func (mock *StoreMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CreateOrUpdateDevice calls CreateOrUpdateDeviceFunc.
func (mock *StoreMock) CreateOrUpdateDevice(ctx context.Context, d types.Device) error {
	if mock.CreateOrUpdateDeviceFunc == nil {
		panic("StoreMock.CreateOrUpdateDeviceFunc: method is nil but Store.CreateOrUpdateDevice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		D   types.Device
	}{
		Ctx: ctx,
		D:   d,
	}
	mock.lockCreateOrUpdateDevice.Lock()
	mock.calls.CreateOrUpdateDevice = append(mock.calls.CreateOrUpdateDevice, callInfo)
	mock.lockCreateOrUpdateDevice.Unlock()
	return mock.CreateOrUpdateDeviceFunc(ctx, d)
}

// CreateOrUpdateDeviceCalls gets all the calls that were made to CreateOrUpdateDevice.
// Check the length with:
//
//	len(mockedStore.CreateOrUpdateDeviceCalls())
func (mock *StoreMock) CreateOrUpdateDeviceCalls() []struct {
	Ctx context.Context
	D   types.Device
} {
	var calls []struct {
		Ctx context.Context
		D   types.Device
	}
	mock.lockCreateOrUpdateDevice.RLock()
	calls = mock.calls.CreateOrUpdateDevice
	mock.lockCreateOrUpdateDevice.RUnlock()
	return calls
}

// CreateSensorProfile calls CreateSensorProfileFunc.
func (mock *StoreMock) CreateSensorProfile(ctx context.Context, p types.SensorProfile) error {
	if mock.CreateSensorProfileFunc == nil {
		panic("StoreMock.CreateSensorProfileFunc: method is nil but Store.CreateSensorProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   types.SensorProfile
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockCreateSensorProfile.Lock()
	mock.calls.CreateSensorProfile = append(mock.calls.CreateSensorProfile, callInfo)
	mock.lockCreateSensorProfile.Unlock()
	return mock.CreateSensorProfileFunc(ctx, p)
}

// CreateSensorProfileCalls gets all the calls that were made to CreateSensorProfile.
// Check the length with:
//
//	len(mockedStore.CreateSensorProfileCalls())
func (mock *StoreMock) CreateSensorProfileCalls() []struct {
	Ctx context.Context
	P   types.SensorProfile
} {
	var calls []struct {
		Ctx context.Context
		P   types.SensorProfile
	}
	mock.lockCreateSensorProfile.RLock()
	calls = mock.calls.CreateSensorProfile
	mock.lockCreateSensorProfile.RUnlock()
	return calls
}

// CreateSensorProfileType calls CreateSensorProfileTypeFunc.
func (mock *StoreMock) CreateSensorProfileType(ctx context.Context, t types.Lwm2mType) error {
	if mock.CreateSensorProfileTypeFunc == nil {
		panic("StoreMock.CreateSensorProfileTypeFunc: method is nil but Store.CreateSensorProfileType was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   types.Lwm2mType
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockCreateSensorProfileType.Lock()
	mock.calls.CreateSensorProfileType = append(mock.calls.CreateSensorProfileType, callInfo)
	mock.lockCreateSensorProfileType.Unlock()
	return mock.CreateSensorProfileTypeFunc(ctx, t)
}

// CreateSensorProfileTypeCalls gets all the calls that were made to CreateSensorProfileType.
// Check the length with:
//
//	len(mockedStore.CreateSensorProfileTypeCalls())
func (mock *StoreMock) CreateSensorProfileTypeCalls() []struct {
	Ctx context.Context
	T   types.Lwm2mType
} {
	var calls []struct {
		Ctx context.Context
		T   types.Lwm2mType
	}
	mock.lockCreateSensorProfileType.RLock()
	calls = mock.calls.CreateSensorProfileType
	mock.lockCreateSensorProfileType.RUnlock()
	return calls
}

// CreateTag calls CreateTagFunc.
func (mock *StoreMock) CreateTag(ctx context.Context, t types.Tag) error {
	if mock.CreateTagFunc == nil {
		panic("StoreMock.CreateTagFunc: method is nil but Store.CreateTag was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   types.Tag
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockCreateTag.Lock()
	mock.calls.CreateTag = append(mock.calls.CreateTag, callInfo)
	mock.lockCreateTag.Unlock()
	return mock.CreateTagFunc(ctx, t)
}

// CreateTagCalls gets all the calls that were made to CreateTag.
// Check the length with:
//
//	len(mockedStore.CreateTagCalls())
func (mock *StoreMock) CreateTagCalls() []struct {
	Ctx context.Context
	T   types.Tag
} {
	var calls []struct {
		Ctx context.Context
		T   types.Tag
	}
	mock.lockCreateTag.RLock()
	calls = mock.calls.CreateTag
	mock.lockCreateTag.RUnlock()
	return calls
}

// GetAlarms calls GetAlarmsFunc.
func (mock *StoreMock) GetAlarms(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Alarms], error) {
	if mock.GetAlarmsFunc == nil {
		panic("StoreMock.GetAlarmsFunc: method is nil but Store.GetAlarms was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockGetAlarms.Lock()
	mock.calls.GetAlarms = append(mock.calls.GetAlarms, callInfo)
	mock.lockGetAlarms.Unlock()
	return mock.GetAlarmsFunc(ctx, conditionsMoqParam...)
}

// GetAlarmsCalls gets all the calls that were made to GetAlarms.
// Check the length with:
//
//	len(mockedStore.GetAlarmsCalls())
func (mock *StoreMock) GetAlarmsCalls() []struct {
	Ctx                context.Context
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockGetAlarms.RLock()
	calls = mock.calls.GetAlarms
	mock.lockGetAlarms.RUnlock()
	return calls
}

// GetDeviceAlarms calls GetDeviceAlarmsFunc.
func (mock *StoreMock) GetDeviceAlarms(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
	if mock.GetDeviceAlarmsFunc == nil {
		panic("StoreMock.GetDeviceAlarmsFunc: method is nil but Store.GetDeviceAlarms was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockGetDeviceAlarms.Lock()
	mock.calls.GetDeviceAlarms = append(mock.calls.GetDeviceAlarms, callInfo)
	mock.lockGetDeviceAlarms.Unlock()
	return mock.GetDeviceAlarmsFunc(ctx, deviceID)
}

// GetDeviceAlarmsCalls gets all the calls that were made to GetDeviceAlarms.
// Check the length with:
//
//	len(mockedStore.GetDeviceAlarmsCalls())
func (mock *StoreMock) GetDeviceAlarmsCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockGetDeviceAlarms.RLock()
	calls = mock.calls.GetDeviceAlarms
	mock.lockGetDeviceAlarms.RUnlock()
	return calls
}

// GetDeviceBySensorID calls GetDeviceBySensorIDFunc.
func (mock *StoreMock) GetDeviceBySensorID(ctx context.Context, sensorID string) (types.Device, error) {
	if mock.GetDeviceBySensorIDFunc == nil {
		panic("StoreMock.GetDeviceBySensorIDFunc: method is nil but Store.GetDeviceBySensorID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SensorID string
	}{
		Ctx:      ctx,
		SensorID: sensorID,
	}
	mock.lockGetDeviceBySensorID.Lock()
	mock.calls.GetDeviceBySensorID = append(mock.calls.GetDeviceBySensorID, callInfo)
	mock.lockGetDeviceBySensorID.Unlock()
	return mock.GetDeviceBySensorIDFunc(ctx, sensorID)
}

// GetDeviceBySensorIDCalls gets all the calls that were made to GetDeviceBySensorID.
// Check the length with:
//
//	len(mockedStore.GetDeviceBySensorIDCalls())
func (mock *StoreMock) GetDeviceBySensorIDCalls() []struct {
	Ctx      context.Context
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		SensorID string
	}
	mock.lockGetDeviceBySensorID.RLock()
	calls = mock.calls.GetDeviceBySensorID
	mock.lockGetDeviceBySensorID.RUnlock()
	return calls
}

// GetDeviceMeasurements calls GetDeviceMeasurementsFunc.
func (mock *StoreMock) GetDeviceMeasurements(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error) {
	if mock.GetDeviceMeasurementsFunc == nil {
		panic("StoreMock.GetDeviceMeasurementsFunc: method is nil but Store.GetDeviceMeasurements was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		DeviceID:           deviceID,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockGetDeviceMeasurements.Lock()
	mock.calls.GetDeviceMeasurements = append(mock.calls.GetDeviceMeasurements, callInfo)
	mock.lockGetDeviceMeasurements.Unlock()
	return mock.GetDeviceMeasurementsFunc(ctx, deviceID, conditionsMoqParam...)
}

// GetDeviceMeasurementsCalls gets all the calls that were made to GetDeviceMeasurements.
// Check the length with:
//
//	len(mockedStore.GetDeviceMeasurementsCalls())
func (mock *StoreMock) GetDeviceMeasurementsCalls() []struct {
	Ctx                context.Context
	DeviceID           string
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockGetDeviceMeasurements.RLock()
	calls = mock.calls.GetDeviceMeasurements
	mock.lockGetDeviceMeasurements.RUnlock()
	return calls
}

// GetDeviceStatus calls GetDeviceStatusFunc.
func (mock *StoreMock) GetDeviceStatus(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error) {
	if mock.GetDeviceStatusFunc == nil {
		panic("StoreMock.GetDeviceStatusFunc: method is nil but Store.GetDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		DeviceID:           deviceID,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockGetDeviceStatus.Lock()
	mock.calls.GetDeviceStatus = append(mock.calls.GetDeviceStatus, callInfo)
	mock.lockGetDeviceStatus.Unlock()
	return mock.GetDeviceStatusFunc(ctx, deviceID, conditionsMoqParam...)
}

// GetDeviceStatusCalls gets all the calls that were made to GetDeviceStatus.
// Check the length with:
//
//	len(mockedStore.GetDeviceStatusCalls())
func (mock *StoreMock) GetDeviceStatusCalls() []struct {
	Ctx                context.Context
	DeviceID           string
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockGetDeviceStatus.RLock()
	calls = mock.calls.GetDeviceStatus
	mock.lockGetDeviceStatus.RUnlock()
	return calls
}

// GetStaleDevices calls GetStaleDevicesFunc.
func (mock *StoreMock) GetStaleDevices(ctx context.Context) (types.Collection[types.Device], error) {
	if mock.GetStaleDevicesFunc == nil {
		panic("StoreMock.GetStaleDevicesFunc: method is nil but Store.GetStaleDevices was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetStaleDevices.Lock()
	mock.calls.GetStaleDevices = append(mock.calls.GetStaleDevices, callInfo)
	mock.lockGetStaleDevices.Unlock()
	return mock.GetStaleDevicesFunc(ctx)
}

// GetStaleDevicesCalls gets all the calls that were made to GetStaleDevices.
// Check the length with:
//
//	len(mockedStore.GetStaleDevicesCalls())
func (mock *StoreMock) GetStaleDevicesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetStaleDevices.RLock()
	calls = mock.calls.GetStaleDevices
	mock.lockGetStaleDevices.RUnlock()
	return calls
}

// GetTenants calls GetTenantsFunc.
func (mock *StoreMock) GetTenants(ctx context.Context) (types.Collection[string], error) {
	if mock.GetTenantsFunc == nil {
		panic("StoreMock.GetTenantsFunc: method is nil but Store.GetTenants was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTenants.Lock()
	mock.calls.GetTenants = append(mock.calls.GetTenants, callInfo)
	mock.lockGetTenants.Unlock()
	return mock.GetTenantsFunc(ctx)
}

// GetTenantsCalls gets all the calls that were made to GetTenants.
// Check the length with:
//
//	len(mockedStore.GetTenantsCalls())
func (mock *StoreMock) GetTenantsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTenants.RLock()
	calls = mock.calls.GetTenants
	mock.lockGetTenants.RUnlock()
	return calls
}

// Initialize calls InitializeFunc.
func (mock *StoreMock) Initialize(ctx context.Context) error {
	if mock.InitializeFunc == nil {
		panic("StoreMock.InitializeFunc: method is nil but Store.Initialize was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	mock.lockInitialize.Unlock()
	return mock.InitializeFunc(ctx)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//
//	len(mockedStore.InitializeCalls())
func (mock *StoreMock) InitializeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockInitialize.RLock()
	calls = mock.calls.Initialize
	mock.lockInitialize.RUnlock()
	return calls
}

// IsSeedExistingDevicesEnabled calls IsSeedExistingDevicesEnabledFunc.
func (mock *StoreMock) IsSeedExistingDevicesEnabled(ctx context.Context) bool {
	if mock.IsSeedExistingDevicesEnabledFunc == nil {
		panic("StoreMock.IsSeedExistingDevicesEnabledFunc: method is nil but Store.IsSeedExistingDevicesEnabled was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockIsSeedExistingDevicesEnabled.Lock()
	mock.calls.IsSeedExistingDevicesEnabled = append(mock.calls.IsSeedExistingDevicesEnabled, callInfo)
	mock.lockIsSeedExistingDevicesEnabled.Unlock()
	return mock.IsSeedExistingDevicesEnabledFunc(ctx)
}

// IsSeedExistingDevicesEnabledCalls gets all the calls that were made to IsSeedExistingDevicesEnabled.
// Check the length with:
//
//	len(mockedStore.IsSeedExistingDevicesEnabledCalls())
func (mock *StoreMock) IsSeedExistingDevicesEnabledCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockIsSeedExistingDevicesEnabled.RLock()
	calls = mock.calls.IsSeedExistingDevicesEnabled
	mock.lockIsSeedExistingDevicesEnabled.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *StoreMock) Query(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error) {
	if mock.QueryFunc == nil {
		panic("StoreMock.QueryFunc: method is nil but Store.Query was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, conditionsMoqParam...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedStore.QueryCalls())
func (mock *StoreMock) QueryCalls() []struct {
	Ctx                context.Context
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// RemoveAlarm calls RemoveAlarmFunc.
func (mock *StoreMock) RemoveAlarm(ctx context.Context, deviceID string, alarmType string) error {
	if mock.RemoveAlarmFunc == nil {
		panic("StoreMock.RemoveAlarmFunc: method is nil but Store.RemoveAlarm was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}{
		Ctx:       ctx,
		DeviceID:  deviceID,
		AlarmType: alarmType,
	}
	mock.lockRemoveAlarm.Lock()
	mock.calls.RemoveAlarm = append(mock.calls.RemoveAlarm, callInfo)
	mock.lockRemoveAlarm.Unlock()
	return mock.RemoveAlarmFunc(ctx, deviceID, alarmType)
}

// RemoveAlarmCalls gets all the calls that were made to RemoveAlarm.
// Check the length with:
//
//	len(mockedStore.RemoveAlarmCalls())
func (mock *StoreMock) RemoveAlarmCalls() []struct {
	Ctx       context.Context
	DeviceID  string
	AlarmType string
} {
	var calls []struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}
	mock.lockRemoveAlarm.RLock()
	calls = mock.calls.RemoveAlarm
	mock.lockRemoveAlarm.RUnlock()
	return calls
}

// SetDeviceProfileTypes calls SetDeviceProfileTypesFunc.
func (mock *StoreMock) SetDeviceProfileTypes(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
	if mock.SetDeviceProfileTypesFunc == nil {
		panic("StoreMock.SetDeviceProfileTypesFunc: method is nil but Store.SetDeviceProfileTypes was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}{
		Ctx:           ctx,
		DeviceID:      deviceID,
		TypesMoqParam: typesMoqParam,
	}
	mock.lockSetDeviceProfileTypes.Lock()
	mock.calls.SetDeviceProfileTypes = append(mock.calls.SetDeviceProfileTypes, callInfo)
	mock.lockSetDeviceProfileTypes.Unlock()
	return mock.SetDeviceProfileTypesFunc(ctx, deviceID, typesMoqParam)
}

// SetDeviceProfileTypesCalls gets all the calls that were made to SetDeviceProfileTypes.
// Check the length with:
//
//	len(mockedStore.SetDeviceProfileTypesCalls())
func (mock *StoreMock) SetDeviceProfileTypesCalls() []struct {
	Ctx           context.Context
	DeviceID      string
	TypesMoqParam []types.Lwm2mType
} {
	var calls []struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}
	mock.lockSetDeviceProfileTypes.RLock()
	calls = mock.calls.SetDeviceProfileTypes
	mock.lockSetDeviceProfileTypes.RUnlock()
	return calls
}

// SetDeviceState calls SetDeviceStateFunc.
func (mock *StoreMock) SetDeviceState(ctx context.Context, deviceID string, state types.DeviceState) error {
	if mock.SetDeviceStateFunc == nil {
		panic("StoreMock.SetDeviceStateFunc: method is nil but Store.SetDeviceState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		State:    state,
	}
	mock.lockSetDeviceState.Lock()
	mock.calls.SetDeviceState = append(mock.calls.SetDeviceState, callInfo)
	mock.lockSetDeviceState.Unlock()
	return mock.SetDeviceStateFunc(ctx, deviceID, state)
}

// SetDeviceStateCalls gets all the calls that were made to SetDeviceState.
// Check the length with:
//
//	len(mockedStore.SetDeviceStateCalls())
func (mock *StoreMock) SetDeviceStateCalls() []struct {
	Ctx      context.Context
	DeviceID string
	State    types.DeviceState
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}
	mock.lockSetDeviceState.RLock()
	calls = mock.calls.SetDeviceState
	mock.lockSetDeviceState.RUnlock()
	return calls
}

// SetSensorProfile calls SetSensorProfileFunc.
func (mock *StoreMock) SetSensorProfile(ctx context.Context, deviceID string, dp types.SensorProfile) error {
	if mock.SetSensorProfileFunc == nil {
		panic("StoreMock.SetSensorProfileFunc: method is nil but Store.SetSensorProfile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Dp:       dp,
	}
	mock.lockSetSensorProfile.Lock()
	mock.calls.SetSensorProfile = append(mock.calls.SetSensorProfile, callInfo)
	mock.lockSetSensorProfile.Unlock()
	return mock.SetSensorProfileFunc(ctx, deviceID, dp)
}

// SetSensorProfileCalls gets all the calls that were made to SetSensorProfile.
// Check the length with:
//
//	len(mockedStore.SetSensorProfileCalls())
func (mock *StoreMock) SetSensorProfileCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Dp       types.SensorProfile
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}
	mock.lockSetSensorProfile.RLock()
	calls = mock.calls.SetSensorProfile
	mock.lockSetSensorProfile.RUnlock()
	return calls
}

// UpdateDevice calls UpdateDeviceFunc.
func (mock *StoreMock) UpdateDevice(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
	if mock.UpdateDeviceFunc == nil {
		panic("StoreMock.UpdateDeviceFunc: method is nil but Store.UpdateDevice was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}{
		Ctx:         ctx,
		DeviceID:    deviceID,
		Active:      active,
		Name:        name,
		Description: description,
		Environment: environment,
		Source:      source,
		Tenant:      tenant,
		Location:    location,
		Interval:    interval,
	}
	mock.lockUpdateDevice.Lock()
	mock.calls.UpdateDevice = append(mock.calls.UpdateDevice, callInfo)
	mock.lockUpdateDevice.Unlock()
	return mock.UpdateDeviceFunc(ctx, deviceID, active, name, description, environment, source, tenant, location, interval)
}

// UpdateDeviceCalls gets all the calls that were made to UpdateDevice.
// Check the length with:
//
//	len(mockedStore.UpdateDeviceCalls())
func (mock *StoreMock) UpdateDeviceCalls() []struct {
	Ctx         context.Context
	DeviceID    string
	Active      *bool
	Name        *string
	Description *string
	Environment *string
	Source      *string
	Tenant      *string
	Location    *types.Location
	Interval    *int
} {
	var calls []struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}
	mock.lockUpdateDevice.RLock()
	calls = mock.calls.UpdateDevice
	mock.lockUpdateDevice.RUnlock()
	return calls
}
