// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devices

import (
	"context"
	"sync"

	"github.com/diwise/iot-device-mgmt/pkg/types"
)

// Ensure, that DeviceStatusWriterMock does implement DeviceStatusWriter.
// If this is not the case, regenerate this file with moq.
var _ DeviceStatusWriter = &DeviceStatusWriterMock{}

// DeviceStatusWriterMock is a mock implementation of DeviceStatusWriter.
//
//	func TestSomethingThatUsesDeviceStatusWriter(t *testing.T) {
//
//		// make and configure a mocked DeviceStatusWriter
//		mockedDeviceStatusWriter := &DeviceStatusWriterMock{
//			AddDeviceStatusFunc: func(ctx context.Context, status types.StatusMessage) error {
//				panic("mock out the AddDeviceStatus method")
//			},
//			SetDeviceStateFunc: func(ctx context.Context, deviceID string, state types.DeviceState) error {
//				panic("mock out the SetDeviceState method")
//			},
//		}
//
//		// use mockedDeviceStatusWriter in code that requires DeviceStatusWriter
//		// and then make assertions.
//
//	}
type DeviceStatusWriterMock struct {
	// AddDeviceStatusFunc mocks the AddDeviceStatus method.
	AddDeviceStatusFunc func(ctx context.Context, status types.StatusMessage) error

	// SetDeviceStateFunc mocks the SetDeviceState method.
	SetDeviceStateFunc func(ctx context.Context, deviceID string, state types.DeviceState) error

	// calls tracks calls to the methods.
	calls struct {
		// AddDeviceStatus holds details about calls to the AddDeviceStatus method.
		AddDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status types.StatusMessage
		}
		// SetDeviceState holds details about calls to the SetDeviceState method.
		SetDeviceState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// State is the state argument value.
			State types.DeviceState
		}
	}
	lockAddDeviceStatus sync.RWMutex
	lockSetDeviceState  sync.RWMutex
}

// AddDeviceStatus calls AddDeviceStatusFunc.
func (mock *DeviceStatusWriterMock) AddDeviceStatus(ctx context.Context, status types.StatusMessage) error {
	if mock.AddDeviceStatusFunc == nil {
		panic("DeviceStatusWriterMock.AddDeviceStatusFunc: method is nil but DeviceStatusWriter.AddDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status types.StatusMessage
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockAddDeviceStatus.Lock()
	mock.calls.AddDeviceStatus = append(mock.calls.AddDeviceStatus, callInfo)
	mock.lockAddDeviceStatus.Unlock()
	return mock.AddDeviceStatusFunc(ctx, status)
}

// AddDeviceStatusCalls gets all the calls that were made to AddDeviceStatus.
// Check the length with:
//
//	len(mockedDeviceStatusWriter.AddDeviceStatusCalls())
func (mock *DeviceStatusWriterMock) AddDeviceStatusCalls() []struct {
	Ctx    context.Context
	Status types.StatusMessage
} {
	var calls []struct {
		Ctx    context.Context
		Status types.StatusMessage
	}
	mock.lockAddDeviceStatus.RLock()
	calls = mock.calls.AddDeviceStatus
	mock.lockAddDeviceStatus.RUnlock()
	return calls
}

// SetDeviceState calls SetDeviceStateFunc.
func (mock *DeviceStatusWriterMock) SetDeviceState(ctx context.Context, deviceID string, state types.DeviceState) error {
	if mock.SetDeviceStateFunc == nil {
		panic("DeviceStatusWriterMock.SetDeviceStateFunc: method is nil but DeviceStatusWriter.SetDeviceState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		State:    state,
	}
	mock.lockSetDeviceState.Lock()
	mock.calls.SetDeviceState = append(mock.calls.SetDeviceState, callInfo)
	mock.lockSetDeviceState.Unlock()
	return mock.SetDeviceStateFunc(ctx, deviceID, state)
}

// SetDeviceStateCalls gets all the calls that were made to SetDeviceState.
// Check the length with:
//
//	len(mockedDeviceStatusWriter.SetDeviceStateCalls())
func (mock *DeviceStatusWriterMock) SetDeviceStateCalls() []struct {
	Ctx      context.Context
	DeviceID string
	State    types.DeviceState
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}
	mock.lockSetDeviceState.RLock()
	calls = mock.calls.SetDeviceState
	mock.lockSetDeviceState.RUnlock()
	return calls
}
