// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devices

import (
	"context"
	"sync"

	"github.com/diwise/iot-device-mgmt/pkg/types"
)

// Ensure, that DeviceProfileStoreMock does implement DeviceProfileStore.
// If this is not the case, regenerate this file with moq.
var _ DeviceProfileStore = &DeviceProfileStoreMock{}

// DeviceProfileStoreMock is a mock implementation of DeviceProfileStore.
//
//	func TestSomethingThatUsesDeviceProfileStore(t *testing.T) {
//
//		// make and configure a mocked DeviceProfileStore
//		mockedDeviceProfileStore := &DeviceProfileStoreMock{
//			CreateSensorProfileFunc: func(ctx context.Context, p types.SensorProfile) error {
//				panic("mock out the CreateSensorProfile method")
//			},
//			CreateSensorProfileTypeFunc: func(ctx context.Context, t types.Lwm2mType) error {
//				panic("mock out the CreateSensorProfileType method")
//			},
//		}
//
//		// use mockedDeviceProfileStore in code that requires DeviceProfileStore
//		// and then make assertions.
//
//	}
type DeviceProfileStoreMock struct {
	// CreateSensorProfileFunc mocks the CreateSensorProfile method.
	CreateSensorProfileFunc func(ctx context.Context, p types.SensorProfile) error

	// CreateSensorProfileTypeFunc mocks the CreateSensorProfileType method.
	CreateSensorProfileTypeFunc func(ctx context.Context, t types.Lwm2mType) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateSensorProfile holds details about calls to the CreateSensorProfile method.
		CreateSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P types.SensorProfile
		}
		// CreateSensorProfileType holds details about calls to the CreateSensorProfileType method.
		CreateSensorProfileType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T types.Lwm2mType
		}
	}
	lockCreateSensorProfile     sync.RWMutex
	lockCreateSensorProfileType sync.RWMutex
}

// CreateSensorProfile calls CreateSensorProfileFunc.
func (mock *DeviceProfileStoreMock) CreateSensorProfile(ctx context.Context, p types.SensorProfile) error {
	if mock.CreateSensorProfileFunc == nil {
		panic("DeviceProfileStoreMock.CreateSensorProfileFunc: method is nil but DeviceProfileStore.CreateSensorProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   types.SensorProfile
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockCreateSensorProfile.Lock()
	mock.calls.CreateSensorProfile = append(mock.calls.CreateSensorProfile, callInfo)
	mock.lockCreateSensorProfile.Unlock()
	return mock.CreateSensorProfileFunc(ctx, p)
}

// CreateSensorProfileCalls gets all the calls that were made to CreateSensorProfile.
// Check the length with:
//
//	len(mockedDeviceProfileStore.CreateSensorProfileCalls())
func (mock *DeviceProfileStoreMock) CreateSensorProfileCalls() []struct {
	Ctx context.Context
	P   types.SensorProfile
} {
	var calls []struct {
		Ctx context.Context
		P   types.SensorProfile
	}
	mock.lockCreateSensorProfile.RLock()
	calls = mock.calls.CreateSensorProfile
	mock.lockCreateSensorProfile.RUnlock()
	return calls
}

// CreateSensorProfileType calls CreateSensorProfileTypeFunc.
func (mock *DeviceProfileStoreMock) CreateSensorProfileType(ctx context.Context, t types.Lwm2mType) error {
	if mock.CreateSensorProfileTypeFunc == nil {
		panic("DeviceProfileStoreMock.CreateSensorProfileTypeFunc: method is nil but DeviceProfileStore.CreateSensorProfileType was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   types.Lwm2mType
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockCreateSensorProfileType.Lock()
	mock.calls.CreateSensorProfileType = append(mock.calls.CreateSensorProfileType, callInfo)
	mock.lockCreateSensorProfileType.Unlock()
	return mock.CreateSensorProfileTypeFunc(ctx, t)
}

// CreateSensorProfileTypeCalls gets all the calls that were made to CreateSensorProfileType.
// Check the length with:
//
//	len(mockedDeviceProfileStore.CreateSensorProfileTypeCalls())
func (mock *DeviceProfileStoreMock) CreateSensorProfileTypeCalls() []struct {
	Ctx context.Context
	T   types.Lwm2mType
} {
	var calls []struct {
		Ctx context.Context
		T   types.Lwm2mType
	}
	mock.lockCreateSensorProfileType.RLock()
	calls = mock.calls.CreateSensorProfileType
	mock.lockCreateSensorProfileType.RUnlock()
	return calls
}
