// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devices

import (
	"context"
	dmquery "github.com/diwise/iot-device-mgmt/internal/application/devices/query"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that DeviceReaderMock does implement DeviceReader.
// If this is not the case, regenerate this file with moq.
var _ DeviceReader = &DeviceReaderMock{}

// DeviceReaderMock is a mock implementation of DeviceReader.
//
//	func TestSomethingThatUsesDeviceReader(t *testing.T) {
//
//		// make and configure a mocked DeviceReader
//		mockedDeviceReader := &DeviceReaderMock{
//			GetDeviceAlarmsFunc: func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
//				panic("mock out the GetDeviceAlarms method")
//			},
//			GetDeviceBySensorIDFunc: func(ctx context.Context, sensorID string) (types.Device, bool, error) {
//				panic("mock out the GetDeviceBySensorID method")
//			},
//			GetDeviceMeasurementsFunc: func(ctx context.Context, deviceID string, query dmquery.MeasurementFilters) (types.Collection[types.Measurement], error) {
//				panic("mock out the GetDeviceMeasurements method")
//			},
//			GetDeviceStatusFunc: func(ctx context.Context, deviceID string, query dmquery.StatusFilters) (types.Collection[types.SensorStatus], error) {
//				panic("mock out the GetDeviceStatus method")
//			},
//			GetSensorFunc: func(ctx context.Context, sensorID string) (types.Sensor, bool, error) {
//				panic("mock out the GetSensor method")
//			},
//			GetTenantsFunc: func(ctx context.Context) (types.Collection[string], error) {
//				panic("mock out the GetTenants method")
//			},
//			QueryFunc: func(ctx context.Context, query dmquery.DeviceFilters) (types.Collection[types.Device], error) {
//				panic("mock out the Query method")
//			},
//			StaleDevicesFunc: func(ctx context.Context, offset int, limit int, tenants []string) (types.Collection[types.Device], error) {
//				panic("mock out the StaleDevices method")
//			},
//		}
//
//		// use mockedDeviceReader in code that requires DeviceReader
//		// and then make assertions.
//
//	}
type DeviceReaderMock struct {
	// GetDeviceAlarmsFunc mocks the GetDeviceAlarms method.
	GetDeviceAlarmsFunc func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error)

	// GetDeviceBySensorIDFunc mocks the GetDeviceBySensorID method.
	GetDeviceBySensorIDFunc func(ctx context.Context, sensorID string) (types.Device, bool, error)

	// GetDeviceMeasurementsFunc mocks the GetDeviceMeasurements method.
	GetDeviceMeasurementsFunc func(ctx context.Context, deviceID string, query dmquery.MeasurementFilters) (types.Collection[types.Measurement], error)

	// GetDeviceStatusFunc mocks the GetDeviceStatus method.
	GetDeviceStatusFunc func(ctx context.Context, deviceID string, query dmquery.StatusFilters) (types.Collection[types.SensorStatus], error)

	// GetSensorFunc mocks the GetSensor method.
	GetSensorFunc func(ctx context.Context, sensorID string) (types.Sensor, bool, error)

	// GetTenantsFunc mocks the GetTenants method.
	GetTenantsFunc func(ctx context.Context) (types.Collection[string], error)

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, query dmquery.DeviceFilters) (types.Collection[types.Device], error)

	// StaleDevicesFunc mocks the StaleDevices method.
	StaleDevicesFunc func(ctx context.Context, offset int, limit int, tenants []string) (types.Collection[types.Device], error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDeviceAlarms holds details about calls to the GetDeviceAlarms method.
		GetDeviceAlarms []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// GetDeviceBySensorID holds details about calls to the GetDeviceBySensorID method.
		GetDeviceBySensorID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// GetDeviceMeasurements holds details about calls to the GetDeviceMeasurements method.
		GetDeviceMeasurements []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Query is the query argument value.
			Query dmquery.MeasurementFilters
		}
		// GetDeviceStatus holds details about calls to the GetDeviceStatus method.
		GetDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Query is the query argument value.
			Query dmquery.StatusFilters
		}
		// GetSensor holds details about calls to the GetSensor method.
		GetSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// GetTenants holds details about calls to the GetTenants method.
		GetTenants []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query dmquery.DeviceFilters
		}
		// StaleDevices holds details about calls to the StaleDevices method.
		StaleDevices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// Limit is the limit argument value.
			Limit int
			// Tenants is the tenants argument value.
			Tenants []string
		}
	}
	lockGetDeviceAlarms       sync.RWMutex
	lockGetDeviceBySensorID   sync.RWMutex
	lockGetDeviceMeasurements sync.RWMutex
	lockGetDeviceStatus       sync.RWMutex
	lockGetSensor             sync.RWMutex
	lockGetTenants            sync.RWMutex
	lockQuery                 sync.RWMutex
	lockStaleDevices          sync.RWMutex
}

// GetDeviceAlarms calls GetDeviceAlarmsFunc.
func (mock *DeviceReaderMock) GetDeviceAlarms(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
	if mock.GetDeviceAlarmsFunc == nil {
		panic("DeviceReaderMock.GetDeviceAlarmsFunc: method is nil but DeviceReader.GetDeviceAlarms was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockGetDeviceAlarms.Lock()
	mock.calls.GetDeviceAlarms = append(mock.calls.GetDeviceAlarms, callInfo)
	mock.lockGetDeviceAlarms.Unlock()
	return mock.GetDeviceAlarmsFunc(ctx, deviceID)
}

// GetDeviceAlarmsCalls gets all the calls that were made to GetDeviceAlarms.
// Check the length with:
//
//	len(mockedDeviceReader.GetDeviceAlarmsCalls())
func (mock *DeviceReaderMock) GetDeviceAlarmsCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockGetDeviceAlarms.RLock()
	calls = mock.calls.GetDeviceAlarms
	mock.lockGetDeviceAlarms.RUnlock()
	return calls
}

// GetDeviceBySensorID calls GetDeviceBySensorIDFunc.
func (mock *DeviceReaderMock) GetDeviceBySensorID(ctx context.Context, sensorID string) (types.Device, bool, error) {
	if mock.GetDeviceBySensorIDFunc == nil {
		panic("DeviceReaderMock.GetDeviceBySensorIDFunc: method is nil but DeviceReader.GetDeviceBySensorID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SensorID string
	}{
		Ctx:      ctx,
		SensorID: sensorID,
	}
	mock.lockGetDeviceBySensorID.Lock()
	mock.calls.GetDeviceBySensorID = append(mock.calls.GetDeviceBySensorID, callInfo)
	mock.lockGetDeviceBySensorID.Unlock()
	return mock.GetDeviceBySensorIDFunc(ctx, sensorID)
}

// GetDeviceBySensorIDCalls gets all the calls that were made to GetDeviceBySensorID.
// Check the length with:
//
//	len(mockedDeviceReader.GetDeviceBySensorIDCalls())
func (mock *DeviceReaderMock) GetDeviceBySensorIDCalls() []struct {
	Ctx      context.Context
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		SensorID string
	}
	mock.lockGetDeviceBySensorID.RLock()
	calls = mock.calls.GetDeviceBySensorID
	mock.lockGetDeviceBySensorID.RUnlock()
	return calls
}

// GetDeviceMeasurements calls GetDeviceMeasurementsFunc.
func (mock *DeviceReaderMock) GetDeviceMeasurements(ctx context.Context, deviceID string, query dmquery.MeasurementFilters) (types.Collection[types.Measurement], error) {
	if mock.GetDeviceMeasurementsFunc == nil {
		panic("DeviceReaderMock.GetDeviceMeasurementsFunc: method is nil but DeviceReader.GetDeviceMeasurements was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Query    dmquery.MeasurementFilters
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Query:    query,
	}
	mock.lockGetDeviceMeasurements.Lock()
	mock.calls.GetDeviceMeasurements = append(mock.calls.GetDeviceMeasurements, callInfo)
	mock.lockGetDeviceMeasurements.Unlock()
	return mock.GetDeviceMeasurementsFunc(ctx, deviceID, query)
}

// GetDeviceMeasurementsCalls gets all the calls that were made to GetDeviceMeasurements.
// Check the length with:
//
//	len(mockedDeviceReader.GetDeviceMeasurementsCalls())
func (mock *DeviceReaderMock) GetDeviceMeasurementsCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Query    dmquery.MeasurementFilters
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Query    dmquery.MeasurementFilters
	}
	mock.lockGetDeviceMeasurements.RLock()
	calls = mock.calls.GetDeviceMeasurements
	mock.lockGetDeviceMeasurements.RUnlock()
	return calls
}

// GetDeviceStatus calls GetDeviceStatusFunc.
func (mock *DeviceReaderMock) GetDeviceStatus(ctx context.Context, deviceID string, query dmquery.StatusFilters) (types.Collection[types.SensorStatus], error) {
	if mock.GetDeviceStatusFunc == nil {
		panic("DeviceReaderMock.GetDeviceStatusFunc: method is nil but DeviceReader.GetDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Query    dmquery.StatusFilters
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Query:    query,
	}
	mock.lockGetDeviceStatus.Lock()
	mock.calls.GetDeviceStatus = append(mock.calls.GetDeviceStatus, callInfo)
	mock.lockGetDeviceStatus.Unlock()
	return mock.GetDeviceStatusFunc(ctx, deviceID, query)
}

// GetDeviceStatusCalls gets all the calls that were made to GetDeviceStatus.
// Check the length with:
//
//	len(mockedDeviceReader.GetDeviceStatusCalls())
func (mock *DeviceReaderMock) GetDeviceStatusCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Query    dmquery.StatusFilters
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Query    dmquery.StatusFilters
	}
	mock.lockGetDeviceStatus.RLock()
	calls = mock.calls.GetDeviceStatus
	mock.lockGetDeviceStatus.RUnlock()
	return calls
}

// GetSensor calls GetSensorFunc.
func (mock *DeviceReaderMock) GetSensor(ctx context.Context, sensorID string) (types.Sensor, bool, error) {
	if mock.GetSensorFunc == nil {
		panic("DeviceReaderMock.GetSensorFunc: method is nil but DeviceReader.GetSensor was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SensorID string
	}{
		Ctx:      ctx,
		SensorID: sensorID,
	}
	mock.lockGetSensor.Lock()
	mock.calls.GetSensor = append(mock.calls.GetSensor, callInfo)
	mock.lockGetSensor.Unlock()
	return mock.GetSensorFunc(ctx, sensorID)
}

// GetSensorCalls gets all the calls that were made to GetSensor.
// Check the length with:
//
//	len(mockedDeviceReader.GetSensorCalls())
func (mock *DeviceReaderMock) GetSensorCalls() []struct {
	Ctx      context.Context
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		SensorID string
	}
	mock.lockGetSensor.RLock()
	calls = mock.calls.GetSensor
	mock.lockGetSensor.RUnlock()
	return calls
}

// GetTenants calls GetTenantsFunc.
func (mock *DeviceReaderMock) GetTenants(ctx context.Context) (types.Collection[string], error) {
	if mock.GetTenantsFunc == nil {
		panic("DeviceReaderMock.GetTenantsFunc: method is nil but DeviceReader.GetTenants was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTenants.Lock()
	mock.calls.GetTenants = append(mock.calls.GetTenants, callInfo)
	mock.lockGetTenants.Unlock()
	return mock.GetTenantsFunc(ctx)
}

// GetTenantsCalls gets all the calls that were made to GetTenants.
// Check the length with:
//
//	len(mockedDeviceReader.GetTenantsCalls())
func (mock *DeviceReaderMock) GetTenantsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTenants.RLock()
	calls = mock.calls.GetTenants
	mock.lockGetTenants.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *DeviceReaderMock) Query(ctx context.Context, query dmquery.DeviceFilters) (types.Collection[types.Device], error) {
	if mock.QueryFunc == nil {
		panic("DeviceReaderMock.QueryFunc: method is nil but DeviceReader.Query was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query dmquery.DeviceFilters
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, query)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedDeviceReader.QueryCalls())
func (mock *DeviceReaderMock) QueryCalls() []struct {
	Ctx   context.Context
	Query dmquery.DeviceFilters
} {
	var calls []struct {
		Ctx   context.Context
		Query dmquery.DeviceFilters
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// StaleDevices calls StaleDevicesFunc.
func (mock *DeviceReaderMock) StaleDevices(ctx context.Context, offset int, limit int, tenants []string) (types.Collection[types.Device], error) {
	if mock.StaleDevicesFunc == nil {
		panic("DeviceReaderMock.StaleDevicesFunc: method is nil but DeviceReader.StaleDevices was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Offset  int
		Limit   int
		Tenants []string
	}{
		Ctx:     ctx,
		Offset:  offset,
		Limit:   limit,
		Tenants: tenants,
	}
	mock.lockStaleDevices.Lock()
	mock.calls.StaleDevices = append(mock.calls.StaleDevices, callInfo)
	mock.lockStaleDevices.Unlock()
	return mock.StaleDevicesFunc(ctx, offset, limit, tenants)
}

// StaleDevicesCalls gets all the calls that were made to StaleDevices.
// Check the length with:
//
//	len(mockedDeviceReader.StaleDevicesCalls())
func (mock *DeviceReaderMock) StaleDevicesCalls() []struct {
	Ctx     context.Context
	Offset  int
	Limit   int
	Tenants []string
} {
	var calls []struct {
		Ctx     context.Context
		Offset  int
		Limit   int
		Tenants []string
	}
	mock.lockStaleDevices.RLock()
	calls = mock.calls.StaleDevices
	mock.lockStaleDevices.RUnlock()
	return calls
}
