// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package alarms

import (
	"context"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that AlarmServiceMock does implement AlarmService.
// If this is not the case, regenerate this file with moq.
var _ AlarmService = &AlarmServiceMock{}

// AlarmServiceMock is a mock implementation of AlarmService.
//
//	func TestSomethingThatUsesAlarmService(t *testing.T) {
//
//		// make and configure a mocked AlarmService
//		mockedAlarmService := &AlarmServiceMock{
//			AddFunc: func(ctx context.Context, deviceID string, alarm types.Alarm) error {
//				panic("mock out the Add method")
//			},
//			GetStaleDevicesFunc: func(ctx context.Context) (types.Collection[types.Device], error) {
//				panic("mock out the GetStaleDevices method")
//			},
//			RemoveFunc: func(ctx context.Context, deviceID string, alarmType string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedAlarmService in code that requires AlarmService
//		// and then make assertions.
//
//	}
type AlarmServiceMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, deviceID string, alarm types.Alarm) error

	// GetStaleDevicesFunc mocks the GetStaleDevices method.
	GetStaleDevicesFunc func(ctx context.Context) (types.Collection[types.Device], error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, deviceID string, alarmType string) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Alarm is the alarm argument value.
			Alarm types.Alarm
		}
		// GetStaleDevices holds details about calls to the GetStaleDevices method.
		GetStaleDevices []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// AlarmType is the alarmType argument value.
			AlarmType string
		}
	}
	lockAdd             sync.RWMutex
	lockGetStaleDevices sync.RWMutex
	lockRemove          sync.RWMutex
}

// Add calls AddFunc.
func (mock *AlarmServiceMock) Add(ctx context.Context, deviceID string, alarm types.Alarm) error {
	if mock.AddFunc == nil {
		panic("AlarmServiceMock.AddFunc: method is nil but AlarmService.Add was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Alarm    types.Alarm
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Alarm:    alarm,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, deviceID, alarm)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedAlarmService.AddCalls())
func (mock *AlarmServiceMock) AddCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Alarm    types.Alarm
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Alarm    types.Alarm
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// GetStaleDevices calls GetStaleDevicesFunc.
func (mock *AlarmServiceMock) GetStaleDevices(ctx context.Context) (types.Collection[types.Device], error) {
	if mock.GetStaleDevicesFunc == nil {
		panic("AlarmServiceMock.GetStaleDevicesFunc: method is nil but AlarmService.GetStaleDevices was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetStaleDevices.Lock()
	mock.calls.GetStaleDevices = append(mock.calls.GetStaleDevices, callInfo)
	mock.lockGetStaleDevices.Unlock()
	return mock.GetStaleDevicesFunc(ctx)
}

// GetStaleDevicesCalls gets all the calls that were made to GetStaleDevices.
// Check the length with:
//
//	len(mockedAlarmService.GetStaleDevicesCalls())
func (mock *AlarmServiceMock) GetStaleDevicesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetStaleDevices.RLock()
	calls = mock.calls.GetStaleDevices
	mock.lockGetStaleDevices.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *AlarmServiceMock) Remove(ctx context.Context, deviceID string, alarmType string) error {
	if mock.RemoveFunc == nil {
		panic("AlarmServiceMock.RemoveFunc: method is nil but AlarmService.Remove was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}{
		Ctx:       ctx,
		DeviceID:  deviceID,
		AlarmType: alarmType,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, deviceID, alarmType)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedAlarmService.RemoveCalls())
func (mock *AlarmServiceMock) RemoveCalls() []struct {
	Ctx       context.Context
	DeviceID  string
	AlarmType string
} {
	var calls []struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
