// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"context"
	"sync"

	"github.com/diwise/iot-device-mgmt/pkg/types"
	. "github.com/diwise/iot-device-mgmt/pkg/client"
)

// Ensure, that DeviceManagementClientMock does implement DeviceManagementClient.
// If this is not the case, regenerate this file with moq.
var _ DeviceManagementClient = &DeviceManagementClientMock{}

// DeviceManagementClientMock is a mock implementation of DeviceManagementClient.
//
//	func TestSomethingThatUsesDeviceManagementClient(t *testing.T) {
//
//		// make and configure a mocked DeviceManagementClient
//		mockedDeviceManagementClient := &DeviceManagementClientMock{
//			AttachSensorToDeviceFunc: func(ctx context.Context, deviceID string, sensorID string) error {
//				panic("mock out the AttachSensorToDevice method")
//			},
//			CloseFunc: func(ctx context.Context)  {
//				panic("mock out the Close method")
//			},
//			CreateDeviceFunc: func(ctx context.Context, device types.Device) error {
//				panic("mock out the CreateDevice method")
//			},
//			CreateSensorFunc: func(ctx context.Context, sensor types.SensorConfig) error {
//				panic("mock out the CreateSensor method")
//			},
//			DetachSensorFromDeviceFunc: func(ctx context.Context, deviceID string) error {
//				panic("mock out the DetachSensorFromDevice method")
//			},
//			FindDeviceFromDevEUIFunc: func(ctx context.Context, devEUI string) (Device, error) {
//				panic("mock out the FindDeviceFromDevEUI method")
//			},
//			FindDeviceFromInternalIDFunc: func(ctx context.Context, deviceID string) (Device, error) {
//				panic("mock out the FindDeviceFromInternalID method")
//			},
//			GetDeviceProfileFunc: func(ctx context.Context, deviceProfileID string) (*types.SensorProfile, error) {
//				panic("mock out the GetDeviceProfile method")
//			},
//			GetDeviceProfilesFunc: func(ctx context.Context) ([]types.SensorProfile, error) {
//				panic("mock out the GetDeviceProfiles method")
//			},
//			GetSensorFunc: func(ctx context.Context, sensorID string) (Sensor, error) {
//				panic("mock out the GetSensor method")
//			},
//			GetTenantsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the GetTenants method")
//			},
//			ListSensorsFunc: func(ctx context.Context, query types.SensorsQuery) ([]Sensor, error) {
//				panic("mock out the ListSensors method")
//			},
//			UpdateSensorFunc: func(ctx context.Context, sensor types.SensorConfig) error {
//				panic("mock out the UpdateSensor method")
//			},
//		}
//
//		// use mockedDeviceManagementClient in code that requires DeviceManagementClient
//		// and then make assertions.
//
//	}
type DeviceManagementClientMock struct {
	// AttachSensorToDeviceFunc mocks the AttachSensorToDevice method.
	AttachSensorToDeviceFunc func(ctx context.Context, deviceID string, sensorID string) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context)

	// CreateDeviceFunc mocks the CreateDevice method.
	CreateDeviceFunc func(ctx context.Context, device types.Device) error

	// CreateSensorFunc mocks the CreateSensor method.
	CreateSensorFunc func(ctx context.Context, sensor types.SensorConfig) error

	// DetachSensorFromDeviceFunc mocks the DetachSensorFromDevice method.
	DetachSensorFromDeviceFunc func(ctx context.Context, deviceID string) error

	// FindDeviceFromDevEUIFunc mocks the FindDeviceFromDevEUI method.
	FindDeviceFromDevEUIFunc func(ctx context.Context, devEUI string) (Device, error)

	// FindDeviceFromInternalIDFunc mocks the FindDeviceFromInternalID method.
	FindDeviceFromInternalIDFunc func(ctx context.Context, deviceID string) (Device, error)

	// GetDeviceProfileFunc mocks the GetDeviceProfile method.
	GetDeviceProfileFunc func(ctx context.Context, deviceProfileID string) (*types.SensorProfile, error)

	// GetDeviceProfilesFunc mocks the GetDeviceProfiles method.
	GetDeviceProfilesFunc func(ctx context.Context) ([]types.SensorProfile, error)

	// GetSensorFunc mocks the GetSensor method.
	GetSensorFunc func(ctx context.Context, sensorID string) (Sensor, error)

	// GetTenantsFunc mocks the GetTenants method.
	GetTenantsFunc func(ctx context.Context) ([]string, error)

	// ListSensorsFunc mocks the ListSensors method.
	ListSensorsFunc func(ctx context.Context, query types.SensorsQuery) ([]Sensor, error)

	// UpdateSensorFunc mocks the UpdateSensor method.
	UpdateSensorFunc func(ctx context.Context, sensor types.SensorConfig) error

	// calls tracks calls to the methods.
	calls struct {
		// AttachSensorToDevice holds details about calls to the AttachSensorToDevice method.
		AttachSensorToDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CreateDevice holds details about calls to the CreateDevice method.
		CreateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Device is the device argument value.
			Device types.Device
		}
		// CreateSensor holds details about calls to the CreateSensor method.
		CreateSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sensor is the sensor argument value.
			Sensor types.SensorConfig
		}
		// DetachSensorFromDevice holds details about calls to the DetachSensorFromDevice method.
		DetachSensorFromDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// FindDeviceFromDevEUI holds details about calls to the FindDeviceFromDevEUI method.
		FindDeviceFromDevEUI []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DevEUI is the devEUI argument value.
			DevEUI string
		}
		// FindDeviceFromInternalID holds details about calls to the FindDeviceFromInternalID method.
		FindDeviceFromInternalID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// GetDeviceProfile holds details about calls to the GetDeviceProfile method.
		GetDeviceProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceProfileID is the deviceProfileID argument value.
			DeviceProfileID string
		}
		// GetDeviceProfiles holds details about calls to the GetDeviceProfiles method.
		GetDeviceProfiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetSensor holds details about calls to the GetSensor method.
		GetSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// GetTenants holds details about calls to the GetTenants method.
		GetTenants []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListSensors holds details about calls to the ListSensors method.
		ListSensors []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query types.SensorsQuery
		}
		// UpdateSensor holds details about calls to the UpdateSensor method.
		UpdateSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sensor is the sensor argument value.
			Sensor types.SensorConfig
		}
	}
	lockAttachSensorToDevice     sync.RWMutex
	lockClose                    sync.RWMutex
	lockCreateDevice             sync.RWMutex
	lockCreateSensor             sync.RWMutex
	lockDetachSensorFromDevice   sync.RWMutex
	lockFindDeviceFromDevEUI     sync.RWMutex
	lockFindDeviceFromInternalID sync.RWMutex
	lockGetDeviceProfile         sync.RWMutex
	lockGetDeviceProfiles        sync.RWMutex
	lockGetSensor                sync.RWMutex
	lockGetTenants               sync.RWMutex
	lockListSensors              sync.RWMutex
	lockUpdateSensor             sync.RWMutex
}

// AttachSensorToDevice calls AttachSensorToDeviceFunc.
func (mock *DeviceManagementClientMock) AttachSensorToDevice(ctx context.Context, deviceID string, sensorID string) error {
	if mock.AttachSensorToDeviceFunc == nil {
		panic("DeviceManagementClientMock.AttachSensorToDeviceFunc: method is nil but DeviceManagementClient.AttachSensorToDevice was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		SensorID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		SensorID: sensorID,
	}
	mock.lockAttachSensorToDevice.Lock()
	mock.calls.AttachSensorToDevice = append(mock.calls.AttachSensorToDevice, callInfo)
	mock.lockAttachSensorToDevice.Unlock()
	return mock.AttachSensorToDeviceFunc(ctx, deviceID, sensorID)
}

// AttachSensorToDeviceCalls gets all the calls that were made to AttachSensorToDevice.
// Check the length with:
//
//	len(mockedDeviceManagementClient.AttachSensorToDeviceCalls())
func (mock *DeviceManagementClientMock) AttachSensorToDeviceCalls() []struct {
	Ctx      context.Context
	DeviceID string
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		SensorID string
	}
	mock.lockAttachSensorToDevice.RLock()
	calls = mock.calls.AttachSensorToDevice
	mock.lockAttachSensorToDevice.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *DeviceManagementClientMock) Close(ctx context.Context) {
	if mock.CloseFunc == nil {
		panic("DeviceManagementClientMock.CloseFunc: method is nil but DeviceManagementClient.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedDeviceManagementClient.CloseCalls())
func (mock *DeviceManagementClientMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CreateDevice calls CreateDeviceFunc.
func (mock *DeviceManagementClientMock) CreateDevice(ctx context.Context, device types.Device) error {
	if mock.CreateDeviceFunc == nil {
		panic("DeviceManagementClientMock.CreateDeviceFunc: method is nil but DeviceManagementClient.CreateDevice was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Device types.Device
	}{
		Ctx:    ctx,
		Device: device,
	}
	mock.lockCreateDevice.Lock()
	mock.calls.CreateDevice = append(mock.calls.CreateDevice, callInfo)
	mock.lockCreateDevice.Unlock()
	return mock.CreateDeviceFunc(ctx, device)
}

// CreateDeviceCalls gets all the calls that were made to CreateDevice.
// Check the length with:
//
//	len(mockedDeviceManagementClient.CreateDeviceCalls())
func (mock *DeviceManagementClientMock) CreateDeviceCalls() []struct {
	Ctx    context.Context
	Device types.Device
} {
	var calls []struct {
		Ctx    context.Context
		Device types.Device
	}
	mock.lockCreateDevice.RLock()
	calls = mock.calls.CreateDevice
	mock.lockCreateDevice.RUnlock()
	return calls
}

// CreateSensor calls CreateSensorFunc.
func (mock *DeviceManagementClientMock) CreateSensor(ctx context.Context, sensor types.SensorConfig) error {
	if mock.CreateSensorFunc == nil {
		panic("DeviceManagementClientMock.CreateSensorFunc: method is nil but DeviceManagementClient.CreateSensor was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Sensor types.SensorConfig
	}{
		Ctx:    ctx,
		Sensor: sensor,
	}
	mock.lockCreateSensor.Lock()
	mock.calls.CreateSensor = append(mock.calls.CreateSensor, callInfo)
	mock.lockCreateSensor.Unlock()
	return mock.CreateSensorFunc(ctx, sensor)
}

// CreateSensorCalls gets all the calls that were made to CreateSensor.
// Check the length with:
//
//	len(mockedDeviceManagementClient.CreateSensorCalls())
func (mock *DeviceManagementClientMock) CreateSensorCalls() []struct {
	Ctx    context.Context
	Sensor types.SensorConfig
} {
	var calls []struct {
		Ctx    context.Context
		Sensor types.SensorConfig
	}
	mock.lockCreateSensor.RLock()
	calls = mock.calls.CreateSensor
	mock.lockCreateSensor.RUnlock()
	return calls
}

// DetachSensorFromDevice calls DetachSensorFromDeviceFunc.
func (mock *DeviceManagementClientMock) DetachSensorFromDevice(ctx context.Context, deviceID string) error {
	if mock.DetachSensorFromDeviceFunc == nil {
		panic("DeviceManagementClientMock.DetachSensorFromDeviceFunc: method is nil but DeviceManagementClient.DetachSensorFromDevice was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockDetachSensorFromDevice.Lock()
	mock.calls.DetachSensorFromDevice = append(mock.calls.DetachSensorFromDevice, callInfo)
	mock.lockDetachSensorFromDevice.Unlock()
	return mock.DetachSensorFromDeviceFunc(ctx, deviceID)
}

// DetachSensorFromDeviceCalls gets all the calls that were made to DetachSensorFromDevice.
// Check the length with:
//
//	len(mockedDeviceManagementClient.DetachSensorFromDeviceCalls())
func (mock *DeviceManagementClientMock) DetachSensorFromDeviceCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockDetachSensorFromDevice.RLock()
	calls = mock.calls.DetachSensorFromDevice
	mock.lockDetachSensorFromDevice.RUnlock()
	return calls
}

// FindDeviceFromDevEUI calls FindDeviceFromDevEUIFunc.
func (mock *DeviceManagementClientMock) FindDeviceFromDevEUI(ctx context.Context, devEUI string) (Device, error) {
	if mock.FindDeviceFromDevEUIFunc == nil {
		panic("DeviceManagementClientMock.FindDeviceFromDevEUIFunc: method is nil but DeviceManagementClient.FindDeviceFromDevEUI was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		DevEUI string
	}{
		Ctx:    ctx,
		DevEUI: devEUI,
	}
	mock.lockFindDeviceFromDevEUI.Lock()
	mock.calls.FindDeviceFromDevEUI = append(mock.calls.FindDeviceFromDevEUI, callInfo)
	mock.lockFindDeviceFromDevEUI.Unlock()
	return mock.FindDeviceFromDevEUIFunc(ctx, devEUI)
}

// FindDeviceFromDevEUICalls gets all the calls that were made to FindDeviceFromDevEUI.
// Check the length with:
//
//	len(mockedDeviceManagementClient.FindDeviceFromDevEUICalls())
func (mock *DeviceManagementClientMock) FindDeviceFromDevEUICalls() []struct {
	Ctx    context.Context
	DevEUI string
} {
	var calls []struct {
		Ctx    context.Context
		DevEUI string
	}
	mock.lockFindDeviceFromDevEUI.RLock()
	calls = mock.calls.FindDeviceFromDevEUI
	mock.lockFindDeviceFromDevEUI.RUnlock()
	return calls
}

// FindDeviceFromInternalID calls FindDeviceFromInternalIDFunc.
func (mock *DeviceManagementClientMock) FindDeviceFromInternalID(ctx context.Context, deviceID string) (Device, error) {
	if mock.FindDeviceFromInternalIDFunc == nil {
		panic("DeviceManagementClientMock.FindDeviceFromInternalIDFunc: method is nil but DeviceManagementClient.FindDeviceFromInternalID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockFindDeviceFromInternalID.Lock()
	mock.calls.FindDeviceFromInternalID = append(mock.calls.FindDeviceFromInternalID, callInfo)
	mock.lockFindDeviceFromInternalID.Unlock()
	return mock.FindDeviceFromInternalIDFunc(ctx, deviceID)
}

// FindDeviceFromInternalIDCalls gets all the calls that were made to FindDeviceFromInternalID.
// Check the length with:
//
//	len(mockedDeviceManagementClient.FindDeviceFromInternalIDCalls())
func (mock *DeviceManagementClientMock) FindDeviceFromInternalIDCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockFindDeviceFromInternalID.RLock()
	calls = mock.calls.FindDeviceFromInternalID
	mock.lockFindDeviceFromInternalID.RUnlock()
	return calls
}

// GetDeviceProfile calls GetDeviceProfileFunc.
func (mock *DeviceManagementClientMock) GetDeviceProfile(ctx context.Context, deviceProfileID string) (*types.SensorProfile, error) {
	if mock.GetDeviceProfileFunc == nil {
		panic("DeviceManagementClientMock.GetDeviceProfileFunc: method is nil but DeviceManagementClient.GetDeviceProfile was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		DeviceProfileID string
	}{
		Ctx:             ctx,
		DeviceProfileID: deviceProfileID,
	}
	mock.lockGetDeviceProfile.Lock()
	mock.calls.GetDeviceProfile = append(mock.calls.GetDeviceProfile, callInfo)
	mock.lockGetDeviceProfile.Unlock()
	return mock.GetDeviceProfileFunc(ctx, deviceProfileID)
}

// GetDeviceProfileCalls gets all the calls that were made to GetDeviceProfile.
// Check the length with:
//
//	len(mockedDeviceManagementClient.GetDeviceProfileCalls())
func (mock *DeviceManagementClientMock) GetDeviceProfileCalls() []struct {
	Ctx             context.Context
	DeviceProfileID string
} {
	var calls []struct {
		Ctx             context.Context
		DeviceProfileID string
	}
	mock.lockGetDeviceProfile.RLock()
	calls = mock.calls.GetDeviceProfile
	mock.lockGetDeviceProfile.RUnlock()
	return calls
}

// GetDeviceProfiles calls GetDeviceProfilesFunc.
func (mock *DeviceManagementClientMock) GetDeviceProfiles(ctx context.Context) ([]types.SensorProfile, error) {
	if mock.GetDeviceProfilesFunc == nil {
		panic("DeviceManagementClientMock.GetDeviceProfilesFunc: method is nil but DeviceManagementClient.GetDeviceProfiles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDeviceProfiles.Lock()
	mock.calls.GetDeviceProfiles = append(mock.calls.GetDeviceProfiles, callInfo)
	mock.lockGetDeviceProfiles.Unlock()
	return mock.GetDeviceProfilesFunc(ctx)
}

// GetDeviceProfilesCalls gets all the calls that were made to GetDeviceProfiles.
// Check the length with:
//
//	len(mockedDeviceManagementClient.GetDeviceProfilesCalls())
func (mock *DeviceManagementClientMock) GetDeviceProfilesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDeviceProfiles.RLock()
	calls = mock.calls.GetDeviceProfiles
	mock.lockGetDeviceProfiles.RUnlock()
	return calls
}

// GetSensor calls GetSensorFunc.
func (mock *DeviceManagementClientMock) GetSensor(ctx context.Context, sensorID string) (Sensor, error) {
	if mock.GetSensorFunc == nil {
		panic("DeviceManagementClientMock.GetSensorFunc: method is nil but DeviceManagementClient.GetSensor was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SensorID string
	}{
		Ctx:      ctx,
		SensorID: sensorID,
	}
	mock.lockGetSensor.Lock()
	mock.calls.GetSensor = append(mock.calls.GetSensor, callInfo)
	mock.lockGetSensor.Unlock()
	return mock.GetSensorFunc(ctx, sensorID)
}

// GetSensorCalls gets all the calls that were made to GetSensor.
// Check the length with:
//
//	len(mockedDeviceManagementClient.GetSensorCalls())
func (mock *DeviceManagementClientMock) GetSensorCalls() []struct {
	Ctx      context.Context
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		SensorID string
	}
	mock.lockGetSensor.RLock()
	calls = mock.calls.GetSensor
	mock.lockGetSensor.RUnlock()
	return calls
}

// GetTenants calls GetTenantsFunc.
func (mock *DeviceManagementClientMock) GetTenants(ctx context.Context) ([]string, error) {
	if mock.GetTenantsFunc == nil {
		panic("DeviceManagementClientMock.GetTenantsFunc: method is nil but DeviceManagementClient.GetTenants was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTenants.Lock()
	mock.calls.GetTenants = append(mock.calls.GetTenants, callInfo)
	mock.lockGetTenants.Unlock()
	return mock.GetTenantsFunc(ctx)
}

// GetTenantsCalls gets all the calls that were made to GetTenants.
// Check the length with:
//
//	len(mockedDeviceManagementClient.GetTenantsCalls())
func (mock *DeviceManagementClientMock) GetTenantsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTenants.RLock()
	calls = mock.calls.GetTenants
	mock.lockGetTenants.RUnlock()
	return calls
}

// ListSensors calls ListSensorsFunc.
func (mock *DeviceManagementClientMock) ListSensors(ctx context.Context, query types.SensorsQuery) ([]Sensor, error) {
	if mock.ListSensorsFunc == nil {
		panic("DeviceManagementClientMock.ListSensorsFunc: method is nil but DeviceManagementClient.ListSensors was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query types.SensorsQuery
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockListSensors.Lock()
	mock.calls.ListSensors = append(mock.calls.ListSensors, callInfo)
	mock.lockListSensors.Unlock()
	return mock.ListSensorsFunc(ctx, query)
}

// ListSensorsCalls gets all the calls that were made to ListSensors.
// Check the length with:
//
//	len(mockedDeviceManagementClient.ListSensorsCalls())
func (mock *DeviceManagementClientMock) ListSensorsCalls() []struct {
	Ctx   context.Context
	Query types.SensorsQuery
} {
	var calls []struct {
		Ctx   context.Context
		Query types.SensorsQuery
	}
	mock.lockListSensors.RLock()
	calls = mock.calls.ListSensors
	mock.lockListSensors.RUnlock()
	return calls
}

// UpdateSensor calls UpdateSensorFunc.
func (mock *DeviceManagementClientMock) UpdateSensor(ctx context.Context, sensor types.SensorConfig) error {
	if mock.UpdateSensorFunc == nil {
		panic("DeviceManagementClientMock.UpdateSensorFunc: method is nil but DeviceManagementClient.UpdateSensor was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Sensor types.SensorConfig
	}{
		Ctx:    ctx,
		Sensor: sensor,
	}
	mock.lockUpdateSensor.Lock()
	mock.calls.UpdateSensor = append(mock.calls.UpdateSensor, callInfo)
	mock.lockUpdateSensor.Unlock()
	return mock.UpdateSensorFunc(ctx, sensor)
}

// UpdateSensorCalls gets all the calls that were made to UpdateSensor.
// Check the length with:
//
//	len(mockedDeviceManagementClient.UpdateSensorCalls())
func (mock *DeviceManagementClientMock) UpdateSensorCalls() []struct {
	Ctx    context.Context
	Sensor types.SensorConfig
} {
	var calls []struct {
		Ctx    context.Context
		Sensor types.SensorConfig
	}
	mock.lockUpdateSensor.RLock()
	calls = mock.calls.UpdateSensor
	mock.lockUpdateSensor.RUnlock()
	return calls
}
