// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devicemanagement

import (
	"context"
	"sync"

	"github.com/diwise/iot-device-mgmt/pkg/types"
)

// Ensure, that DeviceWriterMock does implement DeviceWriter.
// If this is not the case, regenerate this file with moq.
var _ DeviceWriter = &DeviceWriterMock{}

// DeviceWriterMock is a mock implementation of DeviceWriter.
//
//	func TestSomethingThatUsesDeviceWriter(t *testing.T) {
//
//		// make and configure a mocked DeviceWriter
//		mockedDeviceWriter := &DeviceWriterMock{
//			AssignSensorFunc: func(ctx context.Context, deviceID string, sensorID string) error {
//				panic("mock out the AssignSensor method")
//			},
//			CreateOrUpdateDeviceFunc: func(ctx context.Context, d types.Device) error {
//				panic("mock out the CreateOrUpdateDevice method")
//			},
//			SetDeviceProfileTypesFunc: func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
//				panic("mock out the SetDeviceProfileTypes method")
//			},
//			UnassignSensorFunc: func(ctx context.Context, deviceID string) error {
//				panic("mock out the UnassignSensor method")
//			},
//			UpdateDeviceFunc: func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
//				panic("mock out the UpdateDevice method")
//			},
//		}
//
//		// use mockedDeviceWriter in code that requires DeviceWriter
//		// and then make assertions.
//
//	}
type DeviceWriterMock struct {
	// AssignSensorFunc mocks the AssignSensor method.
	AssignSensorFunc func(ctx context.Context, deviceID string, sensorID string) error

	// CreateOrUpdateDeviceFunc mocks the CreateOrUpdateDevice method.
	CreateOrUpdateDeviceFunc func(ctx context.Context, d types.Device) error

	// SetDeviceProfileTypesFunc mocks the SetDeviceProfileTypes method.
	SetDeviceProfileTypesFunc func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error

	// UnassignSensorFunc mocks the UnassignSensor method.
	UnassignSensorFunc func(ctx context.Context, deviceID string) error

	// UpdateDeviceFunc mocks the UpdateDevice method.
	UpdateDeviceFunc func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error

	// calls tracks calls to the methods.
	calls struct {
		// AssignSensor holds details about calls to the AssignSensor method.
		AssignSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// CreateOrUpdateDevice holds details about calls to the CreateOrUpdateDevice method.
		CreateOrUpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// D is the d argument value.
			D types.Device
		}
		// SetDeviceProfileTypes holds details about calls to the SetDeviceProfileTypes method.
		SetDeviceProfileTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// TypesMoqParam is the typesMoqParam argument value.
			TypesMoqParam []types.Lwm2mType
		}
		// UnassignSensor holds details about calls to the UnassignSensor method.
		UnassignSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// UpdateDevice holds details about calls to the UpdateDevice method.
		UpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Active is the active argument value.
			Active *bool
			// Name is the name argument value.
			Name *string
			// Description is the description argument value.
			Description *string
			// Environment is the environment argument value.
			Environment *string
			// Source is the source argument value.
			Source *string
			// Tenant is the tenant argument value.
			Tenant *string
			// Location is the location argument value.
			Location *types.Location
			// Interval is the interval argument value.
			Interval *int
		}
	}
	lockAssignSensor          sync.RWMutex
	lockCreateOrUpdateDevice  sync.RWMutex
	lockSetDeviceProfileTypes sync.RWMutex
	lockUnassignSensor        sync.RWMutex
	lockUpdateDevice          sync.RWMutex
}

// AssignSensor calls AssignSensorFunc.
func (mock *DeviceWriterMock) AssignSensor(ctx context.Context, deviceID string, sensorID string) error {
	if mock.AssignSensorFunc == nil {
		panic("DeviceWriterMock.AssignSensorFunc: method is nil but DeviceWriter.AssignSensor was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		SensorID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		SensorID: sensorID,
	}
	mock.lockAssignSensor.Lock()
	mock.calls.AssignSensor = append(mock.calls.AssignSensor, callInfo)
	mock.lockAssignSensor.Unlock()
	return mock.AssignSensorFunc(ctx, deviceID, sensorID)
}

// AssignSensorCalls gets all the calls that were made to AssignSensor.
// Check the length with:
//
//	len(mockedDeviceWriter.AssignSensorCalls())
func (mock *DeviceWriterMock) AssignSensorCalls() []struct {
	Ctx      context.Context
	DeviceID string
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		SensorID string
	}
	mock.lockAssignSensor.RLock()
	calls = mock.calls.AssignSensor
	mock.lockAssignSensor.RUnlock()
	return calls
}

// CreateOrUpdateDevice calls CreateOrUpdateDeviceFunc.
func (mock *DeviceWriterMock) CreateOrUpdateDevice(ctx context.Context, d types.Device) error {
	if mock.CreateOrUpdateDeviceFunc == nil {
		panic("DeviceWriterMock.CreateOrUpdateDeviceFunc: method is nil but DeviceWriter.CreateOrUpdateDevice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		D   types.Device
	}{
		Ctx: ctx,
		D:   d,
	}
	mock.lockCreateOrUpdateDevice.Lock()
	mock.calls.CreateOrUpdateDevice = append(mock.calls.CreateOrUpdateDevice, callInfo)
	mock.lockCreateOrUpdateDevice.Unlock()
	return mock.CreateOrUpdateDeviceFunc(ctx, d)
}

// CreateOrUpdateDeviceCalls gets all the calls that were made to CreateOrUpdateDevice.
// Check the length with:
//
//	len(mockedDeviceWriter.CreateOrUpdateDeviceCalls())
func (mock *DeviceWriterMock) CreateOrUpdateDeviceCalls() []struct {
	Ctx context.Context
	D   types.Device
} {
	var calls []struct {
		Ctx context.Context
		D   types.Device
	}
	mock.lockCreateOrUpdateDevice.RLock()
	calls = mock.calls.CreateOrUpdateDevice
	mock.lockCreateOrUpdateDevice.RUnlock()
	return calls
}

// SetDeviceProfileTypes calls SetDeviceProfileTypesFunc.
func (mock *DeviceWriterMock) SetDeviceProfileTypes(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
	if mock.SetDeviceProfileTypesFunc == nil {
		panic("DeviceWriterMock.SetDeviceProfileTypesFunc: method is nil but DeviceWriter.SetDeviceProfileTypes was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}{
		Ctx:           ctx,
		DeviceID:      deviceID,
		TypesMoqParam: typesMoqParam,
	}
	mock.lockSetDeviceProfileTypes.Lock()
	mock.calls.SetDeviceProfileTypes = append(mock.calls.SetDeviceProfileTypes, callInfo)
	mock.lockSetDeviceProfileTypes.Unlock()
	return mock.SetDeviceProfileTypesFunc(ctx, deviceID, typesMoqParam)
}

// SetDeviceProfileTypesCalls gets all the calls that were made to SetDeviceProfileTypes.
// Check the length with:
//
//	len(mockedDeviceWriter.SetDeviceProfileTypesCalls())
func (mock *DeviceWriterMock) SetDeviceProfileTypesCalls() []struct {
	Ctx           context.Context
	DeviceID      string
	TypesMoqParam []types.Lwm2mType
} {
	var calls []struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}
	mock.lockSetDeviceProfileTypes.RLock()
	calls = mock.calls.SetDeviceProfileTypes
	mock.lockSetDeviceProfileTypes.RUnlock()
	return calls
}

// UnassignSensor calls UnassignSensorFunc.
func (mock *DeviceWriterMock) UnassignSensor(ctx context.Context, deviceID string) error {
	if mock.UnassignSensorFunc == nil {
		panic("DeviceWriterMock.UnassignSensorFunc: method is nil but DeviceWriter.UnassignSensor was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockUnassignSensor.Lock()
	mock.calls.UnassignSensor = append(mock.calls.UnassignSensor, callInfo)
	mock.lockUnassignSensor.Unlock()
	return mock.UnassignSensorFunc(ctx, deviceID)
}

// UnassignSensorCalls gets all the calls that were made to UnassignSensor.
// Check the length with:
//
//	len(mockedDeviceWriter.UnassignSensorCalls())
func (mock *DeviceWriterMock) UnassignSensorCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockUnassignSensor.RLock()
	calls = mock.calls.UnassignSensor
	mock.lockUnassignSensor.RUnlock()
	return calls
}

// UpdateDevice calls UpdateDeviceFunc.
func (mock *DeviceWriterMock) UpdateDevice(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
	if mock.UpdateDeviceFunc == nil {
		panic("DeviceWriterMock.UpdateDeviceFunc: method is nil but DeviceWriter.UpdateDevice was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}{
		Ctx:         ctx,
		DeviceID:    deviceID,
		Active:      active,
		Name:        name,
		Description: description,
		Environment: environment,
		Source:      source,
		Tenant:      tenant,
		Location:    location,
		Interval:    interval,
	}
	mock.lockUpdateDevice.Lock()
	mock.calls.UpdateDevice = append(mock.calls.UpdateDevice, callInfo)
	mock.lockUpdateDevice.Unlock()
	return mock.UpdateDeviceFunc(ctx, deviceID, active, name, description, environment, source, tenant, location, interval)
}

// UpdateDeviceCalls gets all the calls that were made to UpdateDevice.
// Check the length with:
//
//	len(mockedDeviceWriter.UpdateDeviceCalls())
func (mock *DeviceWriterMock) UpdateDeviceCalls() []struct {
	Ctx         context.Context
	DeviceID    string
	Active      *bool
	Name        *string
	Description *string
	Environment *string
	Source      *string
	Tenant      *string
	Location    *types.Location
	Interval    *int
} {
	var calls []struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}
	mock.lockUpdateDevice.RLock()
	calls = mock.calls.UpdateDevice
	mock.lockUpdateDevice.RUnlock()
	return calls
}
