// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devicemanagement

import (
	"context"
	conditions "github.com/diwise/iot-device-mgmt/internal/pkg/types"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that DeviceStorageMock does implement DeviceStorage.
// If this is not the case, regenerate this file with moq.
var _ DeviceStorage = &DeviceStorageMock{}

// DeviceStorageMock is a mock implementation of DeviceStorage.
//
//	func TestSomethingThatUsesDeviceStorage(t *testing.T) {
//
//		// make and configure a mocked DeviceStorage
//		mockedDeviceStorage := &DeviceStorageMock{
//			AddDeviceStatusFunc: func(ctx context.Context, status types.StatusMessage) error {
//				panic("mock out the AddDeviceStatus method")
//			},
//			CreateOrUpdateDeviceFunc: func(ctx context.Context, d types.Device) error {
//				panic("mock out the CreateOrUpdateDevice method")
//			},
//			CreateSensorProfileFunc: func(ctx context.Context, p types.SensorProfile) error {
//				panic("mock out the CreateSensorProfile method")
//			},
//			CreateSensorProfileTypeFunc: func(ctx context.Context, t types.Lwm2mType) error {
//				panic("mock out the CreateSensorProfileType method")
//			},
//			GetDeviceAlarmsFunc: func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
//				panic("mock out the GetDeviceAlarms method")
//			},
//			GetDeviceBySensorIDFunc: func(ctx context.Context, sensorID string) (types.Device, error) {
//				panic("mock out the GetDeviceBySensorID method")
//			},
//			GetDeviceMeasurementsFunc: func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error) {
//				panic("mock out the GetDeviceMeasurements method")
//			},
//			GetDeviceStatusFunc: func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error) {
//				panic("mock out the GetDeviceStatus method")
//			},
//			GetTenantsFunc: func(ctx context.Context) (types.Collection[string], error) {
//				panic("mock out the GetTenants method")
//			},
//			IsSeedExistingDevicesEnabledFunc: func(ctx context.Context) bool {
//				panic("mock out the IsSeedExistingDevicesEnabled method")
//			},
//			QueryFunc: func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error) {
//				panic("mock out the Query method")
//			},
//			SetDeviceProfileTypesFunc: func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
//				panic("mock out the SetDeviceProfileTypes method")
//			},
//			SetDeviceStateFunc: func(ctx context.Context, deviceID string, state types.DeviceState) error {
//				panic("mock out the SetDeviceState method")
//			},
//			SetSensorProfileFunc: func(ctx context.Context, deviceID string, dp types.SensorProfile) error {
//				panic("mock out the SetSensorProfile method")
//			},
//			UpdateDeviceFunc: func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
//				panic("mock out the UpdateDevice method")
//			},
//		}
//
//		// use mockedDeviceStorage in code that requires DeviceStorage
//		// and then make assertions.
//
//	}
type DeviceStorageMock struct {
	// AddDeviceStatusFunc mocks the AddDeviceStatus method.
	AddDeviceStatusFunc func(ctx context.Context, status types.StatusMessage) error

	// CreateOrUpdateDeviceFunc mocks the CreateOrUpdateDevice method.
	CreateOrUpdateDeviceFunc func(ctx context.Context, d types.Device) error

	// CreateSensorProfileFunc mocks the CreateSensorProfile method.
	CreateSensorProfileFunc func(ctx context.Context, p types.SensorProfile) error

	// CreateSensorProfileTypeFunc mocks the CreateSensorProfileType method.
	CreateSensorProfileTypeFunc func(ctx context.Context, t types.Lwm2mType) error

	// GetDeviceAlarmsFunc mocks the GetDeviceAlarms method.
	GetDeviceAlarmsFunc func(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error)

	// GetDeviceBySensorIDFunc mocks the GetDeviceBySensorID method.
	GetDeviceBySensorIDFunc func(ctx context.Context, sensorID string) (types.Device, error)

	// GetDeviceMeasurementsFunc mocks the GetDeviceMeasurements method.
	GetDeviceMeasurementsFunc func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error)

	// GetDeviceStatusFunc mocks the GetDeviceStatus method.
	GetDeviceStatusFunc func(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error)

	// GetTenantsFunc mocks the GetTenants method.
	GetTenantsFunc func(ctx context.Context) (types.Collection[string], error)

	// IsSeedExistingDevicesEnabledFunc mocks the IsSeedExistingDevicesEnabled method.
	IsSeedExistingDevicesEnabledFunc func(ctx context.Context) bool

	// QueryFunc mocks the Query method.
	QueryFunc func(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error)

	// SetDeviceProfileTypesFunc mocks the SetDeviceProfileTypes method.
	SetDeviceProfileTypesFunc func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error

	// SetDeviceStateFunc mocks the SetDeviceState method.
	SetDeviceStateFunc func(ctx context.Context, deviceID string, state types.DeviceState) error

	// SetSensorProfileFunc mocks the SetSensorProfile method.
	SetSensorProfileFunc func(ctx context.Context, deviceID string, dp types.SensorProfile) error

	// UpdateDeviceFunc mocks the UpdateDevice method.
	UpdateDeviceFunc func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error

	// calls tracks calls to the methods.
	calls struct {
		// AddDeviceStatus holds details about calls to the AddDeviceStatus method.
		AddDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Status is the status argument value.
			Status types.StatusMessage
		}
		// CreateOrUpdateDevice holds details about calls to the CreateOrUpdateDevice method.
		CreateOrUpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// D is the d argument value.
			D types.Device
		}
		// CreateSensorProfile holds details about calls to the CreateSensorProfile method.
		CreateSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P types.SensorProfile
		}
		// CreateSensorProfileType holds details about calls to the CreateSensorProfileType method.
		CreateSensorProfileType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T types.Lwm2mType
		}
		// GetDeviceAlarms holds details about calls to the GetDeviceAlarms method.
		GetDeviceAlarms []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
		// GetDeviceBySensorID holds details about calls to the GetDeviceBySensorID method.
		GetDeviceBySensorID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SensorID is the sensorID argument value.
			SensorID string
		}
		// GetDeviceMeasurements holds details about calls to the GetDeviceMeasurements method.
		GetDeviceMeasurements []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// GetDeviceStatus holds details about calls to the GetDeviceStatus method.
		GetDeviceStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// GetTenants holds details about calls to the GetTenants method.
		GetTenants []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IsSeedExistingDevicesEnabled holds details about calls to the IsSeedExistingDevicesEnabled method.
		IsSeedExistingDevicesEnabled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Query holds details about calls to the Query method.
		Query []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConditionsMoqParam is the conditionsMoqParam argument value.
			ConditionsMoqParam []conditions.ConditionFunc
		}
		// SetDeviceProfileTypes holds details about calls to the SetDeviceProfileTypes method.
		SetDeviceProfileTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// TypesMoqParam is the typesMoqParam argument value.
			TypesMoqParam []types.Lwm2mType
		}
		// SetDeviceState holds details about calls to the SetDeviceState method.
		SetDeviceState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// State is the state argument value.
			State types.DeviceState
		}
		// SetSensorProfile holds details about calls to the SetSensorProfile method.
		SetSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Dp is the dp argument value.
			Dp types.SensorProfile
		}
		// UpdateDevice holds details about calls to the UpdateDevice method.
		UpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Active is the active argument value.
			Active *bool
			// Name is the name argument value.
			Name *string
			// Description is the description argument value.
			Description *string
			// Environment is the environment argument value.
			Environment *string
			// Source is the source argument value.
			Source *string
			// Tenant is the tenant argument value.
			Tenant *string
			// Location is the location argument value.
			Location *types.Location
			// Interval is the interval argument value.
			Interval *int
		}
	}
	lockAddDeviceStatus              sync.RWMutex
	lockCreateOrUpdateDevice         sync.RWMutex
	lockCreateSensorProfile          sync.RWMutex
	lockCreateSensorProfileType      sync.RWMutex
	lockGetDeviceAlarms              sync.RWMutex
	lockGetDeviceBySensorID          sync.RWMutex
	lockGetDeviceMeasurements        sync.RWMutex
	lockGetDeviceStatus              sync.RWMutex
	lockGetTenants                   sync.RWMutex
	lockIsSeedExistingDevicesEnabled sync.RWMutex
	lockQuery                        sync.RWMutex
	lockSetDeviceProfileTypes        sync.RWMutex
	lockSetDeviceState               sync.RWMutex
	lockSetSensorProfile             sync.RWMutex
	lockUpdateDevice                 sync.RWMutex
}

// AddDeviceStatus calls AddDeviceStatusFunc.
func (mock *DeviceStorageMock) AddDeviceStatus(ctx context.Context, status types.StatusMessage) error {
	if mock.AddDeviceStatusFunc == nil {
		panic("DeviceStorageMock.AddDeviceStatusFunc: method is nil but DeviceStorage.AddDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Status types.StatusMessage
	}{
		Ctx:    ctx,
		Status: status,
	}
	mock.lockAddDeviceStatus.Lock()
	mock.calls.AddDeviceStatus = append(mock.calls.AddDeviceStatus, callInfo)
	mock.lockAddDeviceStatus.Unlock()
	return mock.AddDeviceStatusFunc(ctx, status)
}

// AddDeviceStatusCalls gets all the calls that were made to AddDeviceStatus.
// Check the length with:
//
//	len(mockedDeviceStorage.AddDeviceStatusCalls())
func (mock *DeviceStorageMock) AddDeviceStatusCalls() []struct {
	Ctx    context.Context
	Status types.StatusMessage
} {
	var calls []struct {
		Ctx    context.Context
		Status types.StatusMessage
	}
	mock.lockAddDeviceStatus.RLock()
	calls = mock.calls.AddDeviceStatus
	mock.lockAddDeviceStatus.RUnlock()
	return calls
}

// CreateOrUpdateDevice calls CreateOrUpdateDeviceFunc.
func (mock *DeviceStorageMock) CreateOrUpdateDevice(ctx context.Context, d types.Device) error {
	if mock.CreateOrUpdateDeviceFunc == nil {
		panic("DeviceStorageMock.CreateOrUpdateDeviceFunc: method is nil but DeviceStorage.CreateOrUpdateDevice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		D   types.Device
	}{
		Ctx: ctx,
		D:   d,
	}
	mock.lockCreateOrUpdateDevice.Lock()
	mock.calls.CreateOrUpdateDevice = append(mock.calls.CreateOrUpdateDevice, callInfo)
	mock.lockCreateOrUpdateDevice.Unlock()
	return mock.CreateOrUpdateDeviceFunc(ctx, d)
}

// CreateOrUpdateDeviceCalls gets all the calls that were made to CreateOrUpdateDevice.
// Check the length with:
//
//	len(mockedDeviceStorage.CreateOrUpdateDeviceCalls())
func (mock *DeviceStorageMock) CreateOrUpdateDeviceCalls() []struct {
	Ctx context.Context
	D   types.Device
} {
	var calls []struct {
		Ctx context.Context
		D   types.Device
	}
	mock.lockCreateOrUpdateDevice.RLock()
	calls = mock.calls.CreateOrUpdateDevice
	mock.lockCreateOrUpdateDevice.RUnlock()
	return calls
}

// CreateSensorProfile calls CreateSensorProfileFunc.
func (mock *DeviceStorageMock) CreateSensorProfile(ctx context.Context, p types.SensorProfile) error {
	if mock.CreateSensorProfileFunc == nil {
		panic("DeviceStorageMock.CreateSensorProfileFunc: method is nil but DeviceStorage.CreateSensorProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   types.SensorProfile
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockCreateSensorProfile.Lock()
	mock.calls.CreateSensorProfile = append(mock.calls.CreateSensorProfile, callInfo)
	mock.lockCreateSensorProfile.Unlock()
	return mock.CreateSensorProfileFunc(ctx, p)
}

// CreateSensorProfileCalls gets all the calls that were made to CreateSensorProfile.
// Check the length with:
//
//	len(mockedDeviceStorage.CreateSensorProfileCalls())
func (mock *DeviceStorageMock) CreateSensorProfileCalls() []struct {
	Ctx context.Context
	P   types.SensorProfile
} {
	var calls []struct {
		Ctx context.Context
		P   types.SensorProfile
	}
	mock.lockCreateSensorProfile.RLock()
	calls = mock.calls.CreateSensorProfile
	mock.lockCreateSensorProfile.RUnlock()
	return calls
}

// CreateSensorProfileType calls CreateSensorProfileTypeFunc.
func (mock *DeviceStorageMock) CreateSensorProfileType(ctx context.Context, t types.Lwm2mType) error {
	if mock.CreateSensorProfileTypeFunc == nil {
		panic("DeviceStorageMock.CreateSensorProfileTypeFunc: method is nil but DeviceStorage.CreateSensorProfileType was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   types.Lwm2mType
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockCreateSensorProfileType.Lock()
	mock.calls.CreateSensorProfileType = append(mock.calls.CreateSensorProfileType, callInfo)
	mock.lockCreateSensorProfileType.Unlock()
	return mock.CreateSensorProfileTypeFunc(ctx, t)
}

// CreateSensorProfileTypeCalls gets all the calls that were made to CreateSensorProfileType.
// Check the length with:
//
//	len(mockedDeviceStorage.CreateSensorProfileTypeCalls())
func (mock *DeviceStorageMock) CreateSensorProfileTypeCalls() []struct {
	Ctx context.Context
	T   types.Lwm2mType
} {
	var calls []struct {
		Ctx context.Context
		T   types.Lwm2mType
	}
	mock.lockCreateSensorProfileType.RLock()
	calls = mock.calls.CreateSensorProfileType
	mock.lockCreateSensorProfileType.RUnlock()
	return calls
}

// GetDeviceAlarms calls GetDeviceAlarmsFunc.
func (mock *DeviceStorageMock) GetDeviceAlarms(ctx context.Context, deviceID string) (types.Collection[types.AlarmDetails], error) {
	if mock.GetDeviceAlarmsFunc == nil {
		panic("DeviceStorageMock.GetDeviceAlarmsFunc: method is nil but DeviceStorage.GetDeviceAlarms was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockGetDeviceAlarms.Lock()
	mock.calls.GetDeviceAlarms = append(mock.calls.GetDeviceAlarms, callInfo)
	mock.lockGetDeviceAlarms.Unlock()
	return mock.GetDeviceAlarmsFunc(ctx, deviceID)
}

// GetDeviceAlarmsCalls gets all the calls that were made to GetDeviceAlarms.
// Check the length with:
//
//	len(mockedDeviceStorage.GetDeviceAlarmsCalls())
func (mock *DeviceStorageMock) GetDeviceAlarmsCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockGetDeviceAlarms.RLock()
	calls = mock.calls.GetDeviceAlarms
	mock.lockGetDeviceAlarms.RUnlock()
	return calls
}

// GetDeviceBySensorID calls GetDeviceBySensorIDFunc.
func (mock *DeviceStorageMock) GetDeviceBySensorID(ctx context.Context, sensorID string) (types.Device, error) {
	if mock.GetDeviceBySensorIDFunc == nil {
		panic("DeviceStorageMock.GetDeviceBySensorIDFunc: method is nil but DeviceStorage.GetDeviceBySensorID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		SensorID string
	}{
		Ctx:      ctx,
		SensorID: sensorID,
	}
	mock.lockGetDeviceBySensorID.Lock()
	mock.calls.GetDeviceBySensorID = append(mock.calls.GetDeviceBySensorID, callInfo)
	mock.lockGetDeviceBySensorID.Unlock()
	return mock.GetDeviceBySensorIDFunc(ctx, sensorID)
}

// GetDeviceBySensorIDCalls gets all the calls that were made to GetDeviceBySensorID.
// Check the length with:
//
//	len(mockedDeviceStorage.GetDeviceBySensorIDCalls())
func (mock *DeviceStorageMock) GetDeviceBySensorIDCalls() []struct {
	Ctx      context.Context
	SensorID string
} {
	var calls []struct {
		Ctx      context.Context
		SensorID string
	}
	mock.lockGetDeviceBySensorID.RLock()
	calls = mock.calls.GetDeviceBySensorID
	mock.lockGetDeviceBySensorID.RUnlock()
	return calls
}

// GetDeviceMeasurements calls GetDeviceMeasurementsFunc.
func (mock *DeviceStorageMock) GetDeviceMeasurements(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Measurement], error) {
	if mock.GetDeviceMeasurementsFunc == nil {
		panic("DeviceStorageMock.GetDeviceMeasurementsFunc: method is nil but DeviceStorage.GetDeviceMeasurements was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		DeviceID:           deviceID,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockGetDeviceMeasurements.Lock()
	mock.calls.GetDeviceMeasurements = append(mock.calls.GetDeviceMeasurements, callInfo)
	mock.lockGetDeviceMeasurements.Unlock()
	return mock.GetDeviceMeasurementsFunc(ctx, deviceID, conditionsMoqParam...)
}

// GetDeviceMeasurementsCalls gets all the calls that were made to GetDeviceMeasurements.
// Check the length with:
//
//	len(mockedDeviceStorage.GetDeviceMeasurementsCalls())
func (mock *DeviceStorageMock) GetDeviceMeasurementsCalls() []struct {
	Ctx                context.Context
	DeviceID           string
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockGetDeviceMeasurements.RLock()
	calls = mock.calls.GetDeviceMeasurements
	mock.lockGetDeviceMeasurements.RUnlock()
	return calls
}

// GetDeviceStatus calls GetDeviceStatusFunc.
func (mock *DeviceStorageMock) GetDeviceStatus(ctx context.Context, deviceID string, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.SensorStatus], error) {
	if mock.GetDeviceStatusFunc == nil {
		panic("DeviceStorageMock.GetDeviceStatusFunc: method is nil but DeviceStorage.GetDeviceStatus was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		DeviceID:           deviceID,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockGetDeviceStatus.Lock()
	mock.calls.GetDeviceStatus = append(mock.calls.GetDeviceStatus, callInfo)
	mock.lockGetDeviceStatus.Unlock()
	return mock.GetDeviceStatusFunc(ctx, deviceID, conditionsMoqParam...)
}

// GetDeviceStatusCalls gets all the calls that were made to GetDeviceStatus.
// Check the length with:
//
//	len(mockedDeviceStorage.GetDeviceStatusCalls())
func (mock *DeviceStorageMock) GetDeviceStatusCalls() []struct {
	Ctx                context.Context
	DeviceID           string
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		DeviceID           string
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockGetDeviceStatus.RLock()
	calls = mock.calls.GetDeviceStatus
	mock.lockGetDeviceStatus.RUnlock()
	return calls
}

// GetTenants calls GetTenantsFunc.
func (mock *DeviceStorageMock) GetTenants(ctx context.Context) (types.Collection[string], error) {
	if mock.GetTenantsFunc == nil {
		panic("DeviceStorageMock.GetTenantsFunc: method is nil but DeviceStorage.GetTenants was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTenants.Lock()
	mock.calls.GetTenants = append(mock.calls.GetTenants, callInfo)
	mock.lockGetTenants.Unlock()
	return mock.GetTenantsFunc(ctx)
}

// GetTenantsCalls gets all the calls that were made to GetTenants.
// Check the length with:
//
//	len(mockedDeviceStorage.GetTenantsCalls())
func (mock *DeviceStorageMock) GetTenantsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTenants.RLock()
	calls = mock.calls.GetTenants
	mock.lockGetTenants.RUnlock()
	return calls
}

// IsSeedExistingDevicesEnabled calls IsSeedExistingDevicesEnabledFunc.
func (mock *DeviceStorageMock) IsSeedExistingDevicesEnabled(ctx context.Context) bool {
	if mock.IsSeedExistingDevicesEnabledFunc == nil {
		panic("DeviceStorageMock.IsSeedExistingDevicesEnabledFunc: method is nil but DeviceStorage.IsSeedExistingDevicesEnabled was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockIsSeedExistingDevicesEnabled.Lock()
	mock.calls.IsSeedExistingDevicesEnabled = append(mock.calls.IsSeedExistingDevicesEnabled, callInfo)
	mock.lockIsSeedExistingDevicesEnabled.Unlock()
	return mock.IsSeedExistingDevicesEnabledFunc(ctx)
}

// IsSeedExistingDevicesEnabledCalls gets all the calls that were made to IsSeedExistingDevicesEnabled.
// Check the length with:
//
//	len(mockedDeviceStorage.IsSeedExistingDevicesEnabledCalls())
func (mock *DeviceStorageMock) IsSeedExistingDevicesEnabledCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockIsSeedExistingDevicesEnabled.RLock()
	calls = mock.calls.IsSeedExistingDevicesEnabled
	mock.lockIsSeedExistingDevicesEnabled.RUnlock()
	return calls
}

// Query calls QueryFunc.
func (mock *DeviceStorageMock) Query(ctx context.Context, conditionsMoqParam ...conditions.ConditionFunc) (types.Collection[types.Device], error) {
	if mock.QueryFunc == nil {
		panic("DeviceStorageMock.QueryFunc: method is nil but DeviceStorage.Query was just called")
	}
	callInfo := struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}{
		Ctx:                ctx,
		ConditionsMoqParam: conditionsMoqParam,
	}
	mock.lockQuery.Lock()
	mock.calls.Query = append(mock.calls.Query, callInfo)
	mock.lockQuery.Unlock()
	return mock.QueryFunc(ctx, conditionsMoqParam...)
}

// QueryCalls gets all the calls that were made to Query.
// Check the length with:
//
//	len(mockedDeviceStorage.QueryCalls())
func (mock *DeviceStorageMock) QueryCalls() []struct {
	Ctx                context.Context
	ConditionsMoqParam []conditions.ConditionFunc
} {
	var calls []struct {
		Ctx                context.Context
		ConditionsMoqParam []conditions.ConditionFunc
	}
	mock.lockQuery.RLock()
	calls = mock.calls.Query
	mock.lockQuery.RUnlock()
	return calls
}

// SetDeviceProfileTypes calls SetDeviceProfileTypesFunc.
func (mock *DeviceStorageMock) SetDeviceProfileTypes(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
	if mock.SetDeviceProfileTypesFunc == nil {
		panic("DeviceStorageMock.SetDeviceProfileTypesFunc: method is nil but DeviceStorage.SetDeviceProfileTypes was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}{
		Ctx:           ctx,
		DeviceID:      deviceID,
		TypesMoqParam: typesMoqParam,
	}
	mock.lockSetDeviceProfileTypes.Lock()
	mock.calls.SetDeviceProfileTypes = append(mock.calls.SetDeviceProfileTypes, callInfo)
	mock.lockSetDeviceProfileTypes.Unlock()
	return mock.SetDeviceProfileTypesFunc(ctx, deviceID, typesMoqParam)
}

// SetDeviceProfileTypesCalls gets all the calls that were made to SetDeviceProfileTypes.
// Check the length with:
//
//	len(mockedDeviceStorage.SetDeviceProfileTypesCalls())
func (mock *DeviceStorageMock) SetDeviceProfileTypesCalls() []struct {
	Ctx           context.Context
	DeviceID      string
	TypesMoqParam []types.Lwm2mType
} {
	var calls []struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}
	mock.lockSetDeviceProfileTypes.RLock()
	calls = mock.calls.SetDeviceProfileTypes
	mock.lockSetDeviceProfileTypes.RUnlock()
	return calls
}

// SetDeviceState calls SetDeviceStateFunc.
func (mock *DeviceStorageMock) SetDeviceState(ctx context.Context, deviceID string, state types.DeviceState) error {
	if mock.SetDeviceStateFunc == nil {
		panic("DeviceStorageMock.SetDeviceStateFunc: method is nil but DeviceStorage.SetDeviceState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		State:    state,
	}
	mock.lockSetDeviceState.Lock()
	mock.calls.SetDeviceState = append(mock.calls.SetDeviceState, callInfo)
	mock.lockSetDeviceState.Unlock()
	return mock.SetDeviceStateFunc(ctx, deviceID, state)
}

// SetDeviceStateCalls gets all the calls that were made to SetDeviceState.
// Check the length with:
//
//	len(mockedDeviceStorage.SetDeviceStateCalls())
func (mock *DeviceStorageMock) SetDeviceStateCalls() []struct {
	Ctx      context.Context
	DeviceID string
	State    types.DeviceState
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		State    types.DeviceState
	}
	mock.lockSetDeviceState.RLock()
	calls = mock.calls.SetDeviceState
	mock.lockSetDeviceState.RUnlock()
	return calls
}

// SetSensorProfile calls SetSensorProfileFunc.
func (mock *DeviceStorageMock) SetSensorProfile(ctx context.Context, deviceID string, dp types.SensorProfile) error {
	if mock.SetSensorProfileFunc == nil {
		panic("DeviceStorageMock.SetSensorProfileFunc: method is nil but DeviceStorage.SetSensorProfile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Dp:       dp,
	}
	mock.lockSetSensorProfile.Lock()
	mock.calls.SetSensorProfile = append(mock.calls.SetSensorProfile, callInfo)
	mock.lockSetSensorProfile.Unlock()
	return mock.SetSensorProfileFunc(ctx, deviceID, dp)
}

// SetSensorProfileCalls gets all the calls that were made to SetSensorProfile.
// Check the length with:
//
//	len(mockedDeviceStorage.SetSensorProfileCalls())
func (mock *DeviceStorageMock) SetSensorProfileCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Dp       types.SensorProfile
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}
	mock.lockSetSensorProfile.RLock()
	calls = mock.calls.SetSensorProfile
	mock.lockSetSensorProfile.RUnlock()
	return calls
}

// UpdateDevice calls UpdateDeviceFunc.
func (mock *DeviceStorageMock) UpdateDevice(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
	if mock.UpdateDeviceFunc == nil {
		panic("DeviceStorageMock.UpdateDeviceFunc: method is nil but DeviceStorage.UpdateDevice was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}{
		Ctx:         ctx,
		DeviceID:    deviceID,
		Active:      active,
		Name:        name,
		Description: description,
		Environment: environment,
		Source:      source,
		Tenant:      tenant,
		Location:    location,
		Interval:    interval,
	}
	mock.lockUpdateDevice.Lock()
	mock.calls.UpdateDevice = append(mock.calls.UpdateDevice, callInfo)
	mock.lockUpdateDevice.Unlock()
	return mock.UpdateDeviceFunc(ctx, deviceID, active, name, description, environment, source, tenant, location, interval)
}

// UpdateDeviceCalls gets all the calls that were made to UpdateDevice.
// Check the length with:
//
//	len(mockedDeviceStorage.UpdateDeviceCalls())
func (mock *DeviceStorageMock) UpdateDeviceCalls() []struct {
	Ctx         context.Context
	DeviceID    string
	Active      *bool
	Name        *string
	Description *string
	Environment *string
	Source      *string
	Tenant      *string
	Location    *types.Location
	Interval    *int
} {
	var calls []struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}
	mock.lockUpdateDevice.RLock()
	calls = mock.calls.UpdateDevice
	mock.lockUpdateDevice.RUnlock()
	return calls
}
