// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devicemanagement

import (
	"context"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that DeviceWriterMock does implement DeviceWriter.
// If this is not the case, regenerate this file with moq.
var _ DeviceWriter = &DeviceWriterMock{}

// DeviceWriterMock is a mock implementation of DeviceWriter.
//
//	func TestSomethingThatUsesDeviceWriter(t *testing.T) {
//
//		// make and configure a mocked DeviceWriter
//		mockedDeviceWriter := &DeviceWriterMock{
//			CreateOrUpdateDeviceFunc: func(ctx context.Context, d types.Device) error {
//				panic("mock out the CreateOrUpdateDevice method")
//			},
//			SetDeviceProfileTypesFunc: func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
//				panic("mock out the SetDeviceProfileTypes method")
//			},
//			SetSensorProfileFunc: func(ctx context.Context, deviceID string, dp types.SensorProfile) error {
//				panic("mock out the SetSensorProfile method")
//			},
//			UpdateDeviceFunc: func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
//				panic("mock out the UpdateDevice method")
//			},
//		}
//
//		// use mockedDeviceWriter in code that requires DeviceWriter
//		// and then make assertions.
//
//	}
type DeviceWriterMock struct {
	// CreateOrUpdateDeviceFunc mocks the CreateOrUpdateDevice method.
	CreateOrUpdateDeviceFunc func(ctx context.Context, d types.Device) error

	// SetDeviceProfileTypesFunc mocks the SetDeviceProfileTypes method.
	SetDeviceProfileTypesFunc func(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error

	// SetSensorProfileFunc mocks the SetSensorProfile method.
	SetSensorProfileFunc func(ctx context.Context, deviceID string, dp types.SensorProfile) error

	// UpdateDeviceFunc mocks the UpdateDevice method.
	UpdateDeviceFunc func(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOrUpdateDevice holds details about calls to the CreateOrUpdateDevice method.
		CreateOrUpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// D is the d argument value.
			D types.Device
		}
		// SetDeviceProfileTypes holds details about calls to the SetDeviceProfileTypes method.
		SetDeviceProfileTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// TypesMoqParam is the typesMoqParam argument value.
			TypesMoqParam []types.Lwm2mType
		}
		// SetSensorProfile holds details about calls to the SetSensorProfile method.
		SetSensorProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Dp is the dp argument value.
			Dp types.SensorProfile
		}
		// UpdateDevice holds details about calls to the UpdateDevice method.
		UpdateDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Active is the active argument value.
			Active *bool
			// Name is the name argument value.
			Name *string
			// Description is the description argument value.
			Description *string
			// Environment is the environment argument value.
			Environment *string
			// Source is the source argument value.
			Source *string
			// Tenant is the tenant argument value.
			Tenant *string
			// Location is the location argument value.
			Location *types.Location
			// Interval is the interval argument value.
			Interval *int
		}
	}
	lockCreateOrUpdateDevice  sync.RWMutex
	lockSetDeviceProfileTypes sync.RWMutex
	lockSetSensorProfile      sync.RWMutex
	lockUpdateDevice          sync.RWMutex
}

// CreateOrUpdateDevice calls CreateOrUpdateDeviceFunc.
func (mock *DeviceWriterMock) CreateOrUpdateDevice(ctx context.Context, d types.Device) error {
	if mock.CreateOrUpdateDeviceFunc == nil {
		panic("DeviceWriterMock.CreateOrUpdateDeviceFunc: method is nil but DeviceWriter.CreateOrUpdateDevice was just called")
	}
	callInfo := struct {
		Ctx context.Context
		D   types.Device
	}{
		Ctx: ctx,
		D:   d,
	}
	mock.lockCreateOrUpdateDevice.Lock()
	mock.calls.CreateOrUpdateDevice = append(mock.calls.CreateOrUpdateDevice, callInfo)
	mock.lockCreateOrUpdateDevice.Unlock()
	return mock.CreateOrUpdateDeviceFunc(ctx, d)
}

// CreateOrUpdateDeviceCalls gets all the calls that were made to CreateOrUpdateDevice.
// Check the length with:
//
//	len(mockedDeviceWriter.CreateOrUpdateDeviceCalls())
func (mock *DeviceWriterMock) CreateOrUpdateDeviceCalls() []struct {
	Ctx context.Context
	D   types.Device
} {
	var calls []struct {
		Ctx context.Context
		D   types.Device
	}
	mock.lockCreateOrUpdateDevice.RLock()
	calls = mock.calls.CreateOrUpdateDevice
	mock.lockCreateOrUpdateDevice.RUnlock()
	return calls
}

// SetDeviceProfileTypes calls SetDeviceProfileTypesFunc.
func (mock *DeviceWriterMock) SetDeviceProfileTypes(ctx context.Context, deviceID string, typesMoqParam []types.Lwm2mType) error {
	if mock.SetDeviceProfileTypesFunc == nil {
		panic("DeviceWriterMock.SetDeviceProfileTypesFunc: method is nil but DeviceWriter.SetDeviceProfileTypes was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}{
		Ctx:           ctx,
		DeviceID:      deviceID,
		TypesMoqParam: typesMoqParam,
	}
	mock.lockSetDeviceProfileTypes.Lock()
	mock.calls.SetDeviceProfileTypes = append(mock.calls.SetDeviceProfileTypes, callInfo)
	mock.lockSetDeviceProfileTypes.Unlock()
	return mock.SetDeviceProfileTypesFunc(ctx, deviceID, typesMoqParam)
}

// SetDeviceProfileTypesCalls gets all the calls that were made to SetDeviceProfileTypes.
// Check the length with:
//
//	len(mockedDeviceWriter.SetDeviceProfileTypesCalls())
func (mock *DeviceWriterMock) SetDeviceProfileTypesCalls() []struct {
	Ctx           context.Context
	DeviceID      string
	TypesMoqParam []types.Lwm2mType
} {
	var calls []struct {
		Ctx           context.Context
		DeviceID      string
		TypesMoqParam []types.Lwm2mType
	}
	mock.lockSetDeviceProfileTypes.RLock()
	calls = mock.calls.SetDeviceProfileTypes
	mock.lockSetDeviceProfileTypes.RUnlock()
	return calls
}

// SetSensorProfile calls SetSensorProfileFunc.
func (mock *DeviceWriterMock) SetSensorProfile(ctx context.Context, deviceID string, dp types.SensorProfile) error {
	if mock.SetSensorProfileFunc == nil {
		panic("DeviceWriterMock.SetSensorProfileFunc: method is nil but DeviceWriter.SetSensorProfile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Dp:       dp,
	}
	mock.lockSetSensorProfile.Lock()
	mock.calls.SetSensorProfile = append(mock.calls.SetSensorProfile, callInfo)
	mock.lockSetSensorProfile.Unlock()
	return mock.SetSensorProfileFunc(ctx, deviceID, dp)
}

// SetSensorProfileCalls gets all the calls that were made to SetSensorProfile.
// Check the length with:
//
//	len(mockedDeviceWriter.SetSensorProfileCalls())
func (mock *DeviceWriterMock) SetSensorProfileCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Dp       types.SensorProfile
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Dp       types.SensorProfile
	}
	mock.lockSetSensorProfile.RLock()
	calls = mock.calls.SetSensorProfile
	mock.lockSetSensorProfile.RUnlock()
	return calls
}

// UpdateDevice calls UpdateDeviceFunc.
func (mock *DeviceWriterMock) UpdateDevice(ctx context.Context, deviceID string, active *bool, name *string, description *string, environment *string, source *string, tenant *string, location *types.Location, interval *int) error {
	if mock.UpdateDeviceFunc == nil {
		panic("DeviceWriterMock.UpdateDeviceFunc: method is nil but DeviceWriter.UpdateDevice was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}{
		Ctx:         ctx,
		DeviceID:    deviceID,
		Active:      active,
		Name:        name,
		Description: description,
		Environment: environment,
		Source:      source,
		Tenant:      tenant,
		Location:    location,
		Interval:    interval,
	}
	mock.lockUpdateDevice.Lock()
	mock.calls.UpdateDevice = append(mock.calls.UpdateDevice, callInfo)
	mock.lockUpdateDevice.Unlock()
	return mock.UpdateDeviceFunc(ctx, deviceID, active, name, description, environment, source, tenant, location, interval)
}

// UpdateDeviceCalls gets all the calls that were made to UpdateDevice.
// Check the length with:
//
//	len(mockedDeviceWriter.UpdateDeviceCalls())
func (mock *DeviceWriterMock) UpdateDeviceCalls() []struct {
	Ctx         context.Context
	DeviceID    string
	Active      *bool
	Name        *string
	Description *string
	Environment *string
	Source      *string
	Tenant      *string
	Location    *types.Location
	Interval    *int
} {
	var calls []struct {
		Ctx         context.Context
		DeviceID    string
		Active      *bool
		Name        *string
		Description *string
		Environment *string
		Source      *string
		Tenant      *string
		Location    *types.Location
		Interval    *int
	}
	mock.lockUpdateDevice.RLock()
	calls = mock.calls.UpdateDevice
	mock.lockUpdateDevice.RUnlock()
	return calls
}
