// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package alarms

import (
	"context"
	alarmquery "github.com/diwise/iot-device-mgmt/internal/application/alarms/query"
	"github.com/diwise/iot-device-mgmt/pkg/types"
	"sync"
)

// Ensure, that AlarmAPIServiceMock does implement AlarmAPIService.
// If this is not the case, regenerate this file with moq.
var _ AlarmAPIService = &AlarmAPIServiceMock{}

// AlarmAPIServiceMock is a mock implementation of AlarmAPIService.
//
//	func TestSomethingThatUsesAlarmAPIService(t *testing.T) {
//
//		// make and configure a mocked AlarmAPIService
//		mockedAlarmAPIService := &AlarmAPIServiceMock{
//			AddFunc: func(ctx context.Context, deviceID string, alarm types.AlarmDetails) error {
//				panic("mock out the Add method")
//			},
//			AlarmsFunc: func(ctx context.Context, query alarmquery.Alarms) (types.Collection[types.Alarms], error) {
//				panic("mock out the Alarms method")
//			},
//			RemoveFunc: func(ctx context.Context, deviceID string, alarmType string) error {
//				panic("mock out the Remove method")
//			},
//			StaleFunc: func(ctx context.Context) (types.Collection[types.Device], error) {
//				panic("mock out the Stale method")
//			},
//		}
//
//		// use mockedAlarmAPIService in code that requires AlarmAPIService
//		// and then make assertions.
//
//	}
type AlarmAPIServiceMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, deviceID string, alarm types.AlarmDetails) error

	// AlarmsFunc mocks the Alarms method.
	AlarmsFunc func(ctx context.Context, query alarmquery.Alarms) (types.Collection[types.Alarms], error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, deviceID string, alarmType string) error

	// StaleFunc mocks the Stale method.
	StaleFunc func(ctx context.Context) (types.Collection[types.Device], error)

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// Alarm is the alarm argument value.
			Alarm types.AlarmDetails
		}
		// Alarms holds details about calls to the Alarms method.
		Alarms []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query alarmquery.Alarms
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
			// AlarmType is the alarmType argument value.
			AlarmType string
		}
		// Stale holds details about calls to the Stale method.
		Stale []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAdd    sync.RWMutex
	lockAlarms sync.RWMutex
	lockRemove sync.RWMutex
	lockStale  sync.RWMutex
}

// Add calls AddFunc.
func (mock *AlarmAPIServiceMock) Add(ctx context.Context, deviceID string, alarm types.AlarmDetails) error {
	if mock.AddFunc == nil {
		panic("AlarmAPIServiceMock.AddFunc: method is nil but AlarmAPIService.Add was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
		Alarm    types.AlarmDetails
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
		Alarm:    alarm,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, deviceID, alarm)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedAlarmAPIService.AddCalls())
func (mock *AlarmAPIServiceMock) AddCalls() []struct {
	Ctx      context.Context
	DeviceID string
	Alarm    types.AlarmDetails
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
		Alarm    types.AlarmDetails
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Alarms calls AlarmsFunc.
func (mock *AlarmAPIServiceMock) Alarms(ctx context.Context, query alarmquery.Alarms) (types.Collection[types.Alarms], error) {
	if mock.AlarmsFunc == nil {
		panic("AlarmAPIServiceMock.AlarmsFunc: method is nil but AlarmAPIService.Alarms was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query alarmquery.Alarms
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockAlarms.Lock()
	mock.calls.Alarms = append(mock.calls.Alarms, callInfo)
	mock.lockAlarms.Unlock()
	return mock.AlarmsFunc(ctx, query)
}

// AlarmsCalls gets all the calls that were made to Alarms.
// Check the length with:
//
//	len(mockedAlarmAPIService.AlarmsCalls())
func (mock *AlarmAPIServiceMock) AlarmsCalls() []struct {
	Ctx   context.Context
	Query alarmquery.Alarms
} {
	var calls []struct {
		Ctx   context.Context
		Query alarmquery.Alarms
	}
	mock.lockAlarms.RLock()
	calls = mock.calls.Alarms
	mock.lockAlarms.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *AlarmAPIServiceMock) Remove(ctx context.Context, deviceID string, alarmType string) error {
	if mock.RemoveFunc == nil {
		panic("AlarmAPIServiceMock.RemoveFunc: method is nil but AlarmAPIService.Remove was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}{
		Ctx:       ctx,
		DeviceID:  deviceID,
		AlarmType: alarmType,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, deviceID, alarmType)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedAlarmAPIService.RemoveCalls())
func (mock *AlarmAPIServiceMock) RemoveCalls() []struct {
	Ctx       context.Context
	DeviceID  string
	AlarmType string
} {
	var calls []struct {
		Ctx       context.Context
		DeviceID  string
		AlarmType string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Stale calls StaleFunc.
func (mock *AlarmAPIServiceMock) Stale(ctx context.Context) (types.Collection[types.Device], error) {
	if mock.StaleFunc == nil {
		panic("AlarmAPIServiceMock.StaleFunc: method is nil but AlarmAPIService.Stale was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStale.Lock()
	mock.calls.Stale = append(mock.calls.Stale, callInfo)
	mock.lockStale.Unlock()
	return mock.StaleFunc(ctx)
}

// StaleCalls gets all the calls that were made to Stale.
// Check the length with:
//
//	len(mockedAlarmAPIService.StaleCalls())
func (mock *AlarmAPIServiceMock) StaleCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStale.RLock()
	calls = mock.calls.Stale
	mock.lockStale.RUnlock()
	return calls
}
